### ISSUE TITLE
Problems plotting response file with "inventory.plot()". (TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.)

### ISSUE THREAD

**Issue by joleonar** [obspy/obspy#2673] opened 2020-07-06 21:19 UTC
I'm trying to plot the instrument response that I have I downloaded from IRIS for two stations
Recently I updated the Obspy version to 1.2.0

*Obspy version 1.2.0, Linux Ubuntu 18.04*
*Python 3.6, numpy version 1.18*
*Obspy was updated via*
*(obspy) $ conda update obspy*

```python
t1 = obspy.UTCDateTime("2020-07-01")`
inv = client.get_stations(network="IW", station="PLID", channel="BHZ", level="response", starttime=t1)
inv += client.get_stations(network="GS", station="PR01", channel="HHZ", level="response", starttime=t1)

inv.plot_response(min_freq=1e-3)
```

### *Error message:*

```
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    116     try:
--> 117         num = operator.index(num)
    118     except TypeError:

TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-d39743412a4f> in <module>

----> 3 inv.plot_response(min_freq=1e-3)
      4 inv.write("inventory.xml", format="stationxml")
      5 print(inv)

~/anaconda3/lib/python3.6/site-packages/obspy/core/inventory/inventory.py in plot_response(self, min_freq, output, network, station, location, channel, time, starttime, endtime, axes, unwrap_phase, plot_degrees, show, outfile)
    873                                  unwrap_phase=unwrap_phase,
    874                                  plot_degrees=plot_degrees, show=False,
--> 875                                  outfile=None)
    876                     except ZeroSamplingRate:
    877                         msg = ("Skipping plot of channel with zero "

~/anaconda3/lib/python3.6/site-packages/obspy/core/inventory/channel.py in plot(self, min_freq, output, start_stage, end_stage, label, axes, unwrap_phase, plot_degrees, show, outfile)
    364             axes=axes, sampling_rate=self.sample_rate,
    365             unwrap_phase=unwrap_phase, plot_degrees=plot_degrees, show=show,
--> 366             outfile=outfile)
    367 
    368 

~/anaconda3/lib/python3.6/site-packages/obspy/core/inventory/response.py in plot(self, min_freq, output, start_stage, end_stage, label, axes, sampling_rate, unwrap_phase, plot_degrees, show, outfile)
   1567         cpx_response, freq = self.get_evalresp_response(
   1568             t_samp=t_samp, nfft=nfft, output=output, start_stage=start_stage,
-> 1569             end_stage=end_stage)
   1570 
   1571         if axes:

~/anaconda3/lib/python3.6/site-packages/obspy/core/inventory/response.py in get_evalresp_response(self, t_samp, nfft, output, start_stage, end_stage)
   1426         fy = 1 / (t_samp * 2.0)
   1427         # start at zero to get zero for offset/ DC of fft
-> 1428         freqs = np.linspace(0, fy, nfft // 2 + 1).astype(np.float64)
   1429 
   1430         response = self.get_evalresp_response_for_frequencies(

<__array_function__ internals> in linspace(*args, **kwargs)

~/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    119         raise TypeError(
    120             "object of type {} cannot be safely interpreted as an integer."
--> 121                 .format(type(num)))
    122 
    123     if num < 0:

TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

```
<!--

**Comment by megies** [comment] 2020-07-07 08:05
Works on my end. What's your numpy version?

**Comment by joleonar** [comment] 2020-07-08 20:41
I'm working with **numpy 1.18.1**

**Comment by joleonar** [comment] 2020-07-08 20:52
> Works on my end. What's your numpy version?



> Works on my end. What's your numpy version?

**numpy version 1.18.1**

**Comment by megies** [comment] 2020-07-09 10:50
still cant reproduce 

```
/tmp$ conda list | grep -e obspy -e numpy -e python
numpy                     1.18.1           py36h7314795_1    conda-forge
obspy                     1.2.2            py36h785e9b2_0    conda-forge
python                    3.6.10          h8356626_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
```

**Comment by joleonar** [comment] 2020-07-11 15:40
Thank you for your answer. I'm a little confused about the version of obspy
that I'm using. (I'm sorry because I thought that obspy version was 1.2.0)

When I checked the version directly from the terminal  I get the following

[image: imagen.png]

But when I load the obspy environment I get.

[image: imagen.png]


Two weeks ago I updated obspy using the following command

* conda update obspy*


Now I'm using obspy with jupyter notebook I obtain
[image: imagen.png]



 What should I do?

Again, thank you for the quick response!

**Comment by megies** [comment] 2020-07-11 15:48
those images in your email get lost when github posts your email here..

each Python enviornment only sees the packages installed in itself, not from others. on top of this, even if you have an environment activated, starting `jupyter` might go to a very different environment, dpending how your PATH is set up. if in doubt, use e.g. `which python` or `which jupyter` or `which ipython` to confirm what actually gets started, and when in your Pathon promt, use `print(sys.executable)` (IIRC) to see what Python is actually running.

**Comment by joleonar** [comment] 2020-07-11 20:01
Sorry

I was wrong with Obspy version. I'm  really working with  **Obspy 1.1.0***

I tried to update to version 1.2.0 using  

>> conda update obspy

some others programs were update i.e numpy 1.18.1 --> 1.18.5 but obspy no, as you can see in the following list

>> conda list | grep -e obspy -e numpy -e python
numpy                     1.18.5           py36ha1c710e_0  
numpy-base            1.18.5           py36hde5b4d6_0  
numpydoc               1.1.0                      py_0  
obspy                      1.1.0           py36h3010b51_1002    conda-forge/label/gcc7
python                     3.6.10               h0371630_0  

What do you recommend?

**Comment by megies** [comment] 2020-07-12 10:52
conda sometimes can be a pain with updating packages, sometimes its easiest to make a fresh environment from scratch

**Comment by megies** [comment] 2020-07-12 11:02
I'm closing this for now, since we don't do updates for 1.1.x anymore. Head over to the discourse or gitter if you have problems with your installation that you can't sort out by yourself

**Closed by megies** 2020-07-12 11:02 UTC
Labels: .core.inventory
