### ISSUE TITLE
Can't install obspy with numpy==1.19.0

### ISSUE THREAD

**Issue by maratumba** [obspy/obspy#2654] opened 2020-06-25 10:50 UTC
MacOS Mojave (10.14.6)
Python 3.6.9
obspy 1.2.1

When try to install obspy in a virtual env with pip, latest numpy seems to be causing an error. Downgrading to `numpy==1.18.0` solves the problem.

```sh
$ pip install numpy
Collecting numpy
  Using cached numpy-1.19.0-cp36-cp36m-macosx_10_9_x86_64.whl (15.4 MB)
Installing collected packages: numpy
Successfully installed numpy-1.19.0
$ pip install obspy
Collecting obspy
  Using cached obspy-1.2.1.zip (24.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/username/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c4/ybsr8dyj2xl_7_dlnx3kg8nh0000gn/T/pip-install-f4ljy6y9/obspy/setup.py'"'"'; __file__='"'"'/private/var/folders/c4/ybsr8dyj2xl_7_dlnx3kg8nh0000gn/T/pip-install-f4ljy6y9/obspy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c4/ybsr8dyj2xl_7_dlnx3kg8nh0000gn/T/pip-pip-egg-info-qztu9ujx
         cwd: /private/var/folders/c4/ybsr8dyj2xl_7_dlnx3kg8nh0000gn/T/pip-install-f4ljy6y9/obspy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c4/ybsr8dyj2xl_7_dlnx3kg8nh0000gn/T/pip-install-f4ljy6y9/obspy/setup.py", line 47, in <module>
        from numpy.distutils.core import DistutilsSetupError, setup
    ImportError: cannot import name 'DistutilsSetupError'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by heavelock** [comment] 2020-06-25 11:45
Solved on current master. Duplicate of https://github.com/obspy/obspy/issues/2651

**Closed by heavelock** 2020-06-25 11:45 UTC
