### ISSUE TITLE
getting an error related to newint.py

### ISSUE THREAD

**Issue by kdalbey** [obspy/obspy#2702] opened 2020-08-19 19:28 UTC
Hi I'm running anaconda 5 on windows 10, using a python program that works under python 2.7 and trying to migrate to python 3.7, I get the following error (whether i use pip install obspy or conda install -c conda-forge obspy, I'm an experienced in C/C++/Fortran/MATLAB programmer who is relatively new to python, but wrote some python code (including type hints for better numba performance, which anaconda seems to have not back ported the way canopy did) that I would like to use in the existing project necessitating the move to python 3.x (the project has been meaning to upgrade since python 2.7 is end of life anyway so 2 birds one stone kind of deal).  so can you help me understand  what's happening and how to fix it 

~\AppData\Local\Continuum\anaconda3\envs\my_proj\lib\site-packages\obspy\core\stream.py in merge(self, method, fill_value, interpolation_samples, **kwargs)
   1992                 return -1
   1993 
-> 1994         self._cleanup(**kwargs)
   1995         if method == -1:
   1996             return

~\AppData\Local\Continuum\anaconda3\envs\my_proj\lib\site-packages\obspy\core\stream.py in _cleanup(self, misalignment_threshold)
   2948         """
   2949         # first of all throw away all empty traces
-> 2950         self.traces = [_i for _i in self.traces if _i.stats.npts]
   2951         # check sampling rates and dtypes
   2952         try:

~\AppData\Local\Continuum\anaconda3\envs\my_proj\lib\site-packages\obspy\core\stream.py in <listcomp>(.0)
   2948         """
   2949         # first of all throw away all empty traces
-> 2950         self.traces = [_i for _i in self.traces if _i.stats.npts]
   2951         # check sampling rates and dtypes
   2952         try:

~\AppData\Local\Continuum\anaconda3\envs\my_proj\lib\site-packages\future\types\newint.py in __bool__(self)
    285         So subclasses can override this, Py3-style
    286         """
--> 287         return super(newint, self).__nonzero__()
    288 
    289     def __native__(self):

AttributeError: 'super' object has no attribute '__nonzero__'

**Comment by megies** [comment] 2020-08-20 10:45
`future` is the Python2/3 compatibility helper module we use up to version 1.2.x (not on master branch anymore, which is Python 3 only). I can confirm this and on a first glance it looks like a bug in `future` to me..

```python
python-future/src/future/types/newint.py
 17 if PY3:
 18     long = int
 19     from collections.abc import Iterable
 20 else:
 21     from collections import Iterable
 22 
 23 
 24 class BaseNewInt(type):
 25     def __instancecheck__(cls, instance):
 26         if cls == newint:
 27             # Special case for Py2 short or long int
 28             return isinstance(instance, (int, long))
 29         else:
 30             return issubclass(instance.__class__, cls)
 31 
 32 
 33 class newint(with_metaclass(BaseNewInt, long)):
 34     """
 35     A backport of the Python 3 int object to Py2
 36     """
[...]
280     def __nonzero__(self):
281         return self.__bool__()
282                                         
283     def __bool__(self):
284         """                         
285         So subclasses can override this, Py3-style
286         """
287         return super(newint, self).__nonzero__()
```

In Python 3, `int` builtin (which is the base class for `future`'s `newint`) does not have a `__nonzero__` slot.

I'm really confused though, because if this is really as bad as it seems, it should have surfaced before in our tests..

**Comment by kdalbey** [comment] 2020-08-24 15:37
if it's relevant I'm using anaconda on windows 10
with the visual studio compiler from here
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

I was able to pip install obspy-master.zip (today) but ran into an error in your utcdatetime related to missing "ns" which I presume are nanoseconds

~\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages\obspy\core\trace.py in __setstate__(self, state)
    252         self.__dict__.update(state)
    253         # trigger refreshing
--> 254         self.__setitem__('sampling_rate', state['sampling_rate'])
    255 
    256 

~\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages\obspy\core\trace.py in __setitem__(self, key, value)
    201             else:
    202                 timediff = float(self.npts - 1) * delta
--> 203             self.__dict__['endtime'] = self.starttime + timediff
    204             return
    205         if key == 'component':

~\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages\obspy\core\utcdatetime.py in __add__(self, value)
   1002                    "'UTCDateTime'")
   1003             raise TypeError(msg)
-> 1004         return UTCDateTime(ns=self._ns + int(round(value * 1e9)))
   1005 
   1006     def __sub__(self, value):

~\AppData\Local\Continuum\anaconda3\envs\test\lib\site-packages\obspy\core\utcdatetime.py in _get_ns(self)
    510         :returns: POSIX timestamp as integer nanoseconds
    511         """
--> 512         return self.__ns
    513 
    514     def _set_ns(self, value):

AttributeError: 'UTCDateTime' object has no attribute '_UTCDateTime__ns'

**Comment by kdalbey** [comment] 2020-08-26 17:28
this is the same bug as https://github.com/obspy/obspy/issues/2223

when importing from a pickle file created by obspy < v 1.1.0 you're getting npts as an old version of the integer without __nonzero__

the joint solution to both issues is to modify trace.py

in   def __setitem__(self, key, value): 

circa line 188 change
            elif key == 'npts':
                if not isinstance(value, int):
                    value = int(value)

to
            elif key == 'npts':
                value = int(value)

and change (circa line 250)

    def __setstate__(self, state):
        self.__dict__.update(state)
        # trigger refreshing
        self.__setitem__('sampling_rate', state['sampling_rate'])

to

    def __setstate__(self, state):
        self.__dict__.update(state) 
        # trigger refreshing
        self.__setitem__('starttime', state['starttime'])
        self.__setitem__('sampling_rate', state['sampling_rate'])
        self.__setitem__('npts', state['npts'])

the order of the set items is important  if you don't do start time first you will hit 
https://github.com/obspy/obspy/issues/2223

if you don't don't do npts last you hit either this issue or https://github.com/obspy/obspy/issues/2223 I forget which

**Comment by megies** [comment] 2020-08-28 08:42
So @kdalbey the error you posted above regarding the `newint` was showing up when reading a pickled stream? That changes things massively and would explain how this was not encountered before. Basically a lot of things can be responsible, but usually it is differences in package versions from when the data was pickled and then when it was read again.

Closing this as a duplicate of #2223 then. Please reopen if this was *not* encountered during unpickling.

**Closed by megies** 2020-08-28 08:42 UTC
Labels: PY2/3
