### ISSUE TITLE
error on python 3.7 installation

### ISSUE THREAD

**Issue by pythonmobile** [obspy/obspy#2528] opened 2020-01-05 04:51 UTC
After a pip3 install

```
>>> import obspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uname/.pyenv/versions/3.7.4/lib/python3.7/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/uname/.pyenv/versions/3.7.4/lib/python3.7/site-packages/obspy/core/__init__.py", line 125, in <module>
    from obspy.core.util.attribdict import AttribDict  # NOQA
  File "/home/uname/.pyenv/versions/3.7.4/lib/python3.7/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/uname/.pyenv/versions/3.7.4/lib/python3.7/site-packages/obspy/core/util/base.py", line 397, in <module>
    PROJ4_VERSION = get_proj_version()
  File "/home/uname/.pyenv/versions/3.7.4/lib/python3.7/site-packages/obspy/core/util/base.py", line 383, in get_proj_version
    version_string = str(Proj(proj='utm', zone=10, ellps='WGS84').proj_version)
AttributeError: 'Proj' object has no attribute 'proj_version'
>>> 
```

**Comment by calum-chamberlain** [comment] 2020-01-05 04:55
Duplicate of #2445 and #2449 - pyproj must be < 2.0.

Fixed in #2442

**Closed** 2020-01-05 06:16 UTC
Labels: duplicate
