### ISSUE TITLE
Trace.write generates invalid SAC files under certain conditions

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#1204] opened 2015-12-08 11:50 UTC
This code used to work with ObsPy 0.10.2, but does not work anymore with the new implementation of `obspy.io.sac`:

```python
import numpy as np
from obspy import Trace
from obspy.core import AttribDict

tr = Trace(np.arange(100))
tr.stats.sac = AttribDict()
tr.stats.sac.stla = 1.
tr.stats.sac.stlo = 2.
tr.write('test.sac', format='SAC')
```

The file produced is invalid sac, since some fundamental header field, like `nvhdr` is not set.

The reason for that is that [`obspy_to_sac_header()`](https://github.com/obspy/obspy/blob/master/obspy/io/sac/util.py#L265) detects an existing header and does not set those basic header fields.

I think that the existence of fields `iztype`, `nvhdr`, `leven`, `lovrok`, `iftype` should always be checked and those fields should be set to default values on writing, if they do not exist.

Now, suppose that one sets those fields by hand: there is another problem with start time, which is not taken into account, for the same reason that an existing header is detected.

The following code produces a valid sac file, but with the date-time header fields set to undef. 

```python
import numpy as np
from obspy import Trace, UTCDateTime
from obspy.core import AttribDict

tr = Trace(np.arange(100))
tr.stats.starttime = UTCDateTime()
tr.stats.sac = AttribDict()
tr.stats.sac['iztype'] = 9
tr.stats.sac['nvhdr'] = 6
tr.stats.sac['leven'] = 1
tr.stats.sac['lovrok'] = 1
tr.stats.sac['iftype'] = 1
tr.stats.sac.stla = 1.
tr.stats.sac.stlo = 2.
tr.write('test.sac', format='SAC')
```

Again, I think that we should check on write if the header date-time fields are unset and, in case, set them according to `tr.stats.starttime`.

@jkmacc-LANL What do you think?

**Comment by jkmacc-LANL** [comment] 2015-12-08 14:08
Thanks for this thorough write-up.  This is definitely a regression.  The code you provided would make a good test, to make sure this doesn't happen in the future.  

Your suggestion seems reasonable.  `obspy_to_sac_header` was the trickiest function to write, though, as it had to pass all old tests and provide the new behavior that sought in the rewrite.  I'll give your changes a try, and see how it plays with the hoops that function already jumps through:-)

**Comment by jkmacc-LANL** [comment] 2015-12-08 15:29
I haven't tested a solution yet, but I suspect that putting in default values for missing headers may be in direct conflict with an existing test or two.  For example,  [`test_readXYwriteXYViaObsPy`](https://github.com/obspy/obspy/blob/master/obspy/io/sac/tests/test_core.py#L72) reads an "xy" SAC file with no time headers, writes it, reads it again, and then checks to make sure the content is unchanged.  I think this would fail if header values were put in.  

As it turns out, I was doing this type of time check at one point (see comments in [`SACTrace.to_obspy_trace`](https://github.com/obspy/obspy/blob/master/obspy/io/sac/sactrace.py#L1300) ), but had to comment it out in order to make the tests pass.

I'm not sure why your code worked and the tests passed previously, but these expected behaviors do seem to be in conflict.  Again, I'll know more when I try things out tonight.

**Comment by claudiodsf** [comment] 2015-12-08 15:37
Good point. I don't know why the tests passed previously.
Just to be sure, I double-checked again the above codes with 0.10.2 and they do work properly.

**Comment by claudiodsf** [comment] 2015-12-08 18:13
This issue also applies for `station`, `channel`, `network`, `location` fields.
So, the following code will not save that fields to the sac file.

```python
import numpy as np
from obspy import Trace, UTCDateTime
from obspy.core import AttribDict

tr = Trace(np.arange(100))
tr.stats.starttime = UTCDateTime()
tr.stats.station = 'AAA'
tr.stats.network = 'XX'
tr.stats.channel = 'BHZ'
tr.stats.location = '00'
tr.stats.sac = AttribDict()
tr.stats.sac['iztype'] = 9
tr.stats.sac['nvhdr'] = 6
tr.stats.sac['leven'] = 1
tr.stats.sac['lovrok'] = 1
tr.stats.sac['iftype'] = 1
tr.stats.sac.stla = 1.
tr.stats.sac.stlo = 2.
tr.write('test.sac', format='SAC')
```

**Comment by jkmacc-LANL** [comment] 2015-12-08 18:18
Sorry, just to be clear, are you saying that you expect 'AAA' and 'BHZ' to appear in the SAC header, but they don't?

**Comment by claudiodsf** [comment] 2015-12-08 18:20
Yes, I expect 'AAA',  'XX', 'BHZ' and '00' to be in the header, but the corresponding fields are instead undef.

**Comment by jkmacc-LANL** [comment] 2015-12-08 19:22
Gotcha.  I think `obspy_to_sac_header` does not expect to merge the ObsPy header with the SAC header.  It's just not an easy thing to do and still have the tests pass.  I'll give it another shot.

**Comment by jkmacc-LANL** [comment] 2015-12-10 07:25
Claudio, you were right that your very first code snippet used to work because `io.sac` doesn't set these headers automatically anymore.  I got nervous about changing header values without the user knowing, and I was worried about passing tests:wink:  I think I can change this back so that `iftype`, `leven`, `lovrok`, and `nvhdr` will always get set again, and maybe even be able to set the `kstnm`, `kcmpnm`, etc. from the corresponding `Stats` headers without failing any tests.  Merging `tr.stats` and `tr.stats.sac` gets tricky, which is partly why I chose an "all-or-nothing" approach.

I'm pretty sure I'll have at least one problem, however, involving `iztype` and `starttime`.  In your last code example, you set `iztype = 9` and (I think) assume that `tr.stats.starttime` will become the SAC "nz" reference times.  If an there's an existing `tr.stats.sac` dictionary containing relative times like `a` and `t0`-`t9`, however, those would become invalid if the previous `iztype` wasn't 9, or the Trace had been trimmed or merged.  Additionally, some of the tests involve a SAC file ,`testxy.sac`, with no "nz" times and no `iztype`.  Writing any of these headers automatically would make these tests fail.

I'll give it another try, though, and maybe do a PR with the new (currently failing) test shortly.

**Comment by ThomasLecocq** [comment] 2015-12-10 14:41
Hi,

setting these also fail:
```python
import numpy as np
import obspy
print obspy.__version__
from obspy.core import Stream, Trace, read, AttribDict

filename = 'test.SAC'
a = np.random.random(1000)

t = Trace(data=a)
t.stats.starttime = -120
t.stats.sac = AttribDict()
t.stats.sac.depmin = np.min(a)
t.stats.sac.depmax = np.max(a)
t.stats.sac.depmen = np.mean(a)
st = Stream(traces=[t, ])
st.write(filename, format='SAC')
del st

t = read('test.SAC')
print t
```

```
>pythonw -u "minimal_crash.py"
0.10.2
1 Trace(s) in Stream:
... | 1969-12-31T23:58:00.000000Z - 1970-01-01T00:14:39.000000Z | 1.0 Hz, 1000 samples
>Exit code: 0    Time: 0.710
>pythonw -u "minimal_crash.py"
0.10.3rc1.dev0+1053.g2ed3377ae2.obspy.master
c:\users\tlecocq\desktop\tmp\_obspy\obspy\io\sac\util.py:317: UserWarning: Old header has invalid reftime.
  warnings.warn(msg)
Traceback (most recent call last):
  File "minimal_crash.py", line 21, in <module>
    t = read('test.SAC')
  File "<decorator-gen-29>", line 2, in read
  File "c:\users\tlecocq\desktop\tmp\_obspy\obspy\core\util\decorator.py", line 283, in _map_example_filename
    return func(*args, **kwargs)
  File "c:\users\tlecocq\desktop\tmp\_obspy\obspy\core\stream.py", line 236, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-30>", line 2, in _read
  File "c:\users\tlecocq\desktop\tmp\_obspy\obspy\core\util\decorator.py", line 193, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "c:\users\tlecocq\desktop\tmp\_obspy\obspy\core\stream.py", line 278, in _read
    headonly=headonly, **kwargs)
  File "c:\users\tlecocq\desktop\tmp\_obspy\obspy\core\util\base.py", line 432, in _read_from_plugin
    raise TypeError('Unknown format for file %s' % filename)
TypeError: Unknown format for file test.SAC
>Exit code: 1    Time: 1.408
```

**Comment by jkmacc-LANL** [comment] 2015-12-10 14:59
@ThomasLecocq Does the same thing happen if you also set these?

```python
tr.stats.sac['nvhdr'] = 6
tr.stats.sac['leven'] = 1
tr.stats.sac['lovrok'] = 1
tr.stats.sac['iftype'] = 1
```

**Comment by ThomasLecocq** [comment] 2015-12-10 15:16
@jkmacc-LANL no, it works for those

**Comment by jkmacc-LANL** [comment] 2015-12-15 19:09
All,

In #1206, I put an "if" clause in `util.obspy_to_sac_header` that allows `stats.starttime` to be used as the SAC reference time under the following conditions:

1. No existing valid reference time can be constructed
2. `stats.sac.iztype` is 9
3. No other relative time headers (`t0`-`t9`, `a`, `f`) are set

Also, station, channel, network, and location info from `Stats` are always put into the SAC header, if they aren't already present.

I hope this satisfies previous use cases for which there were no existing tests.

**Comment by krischer** [comment] 2016-01-11 12:57
I assume this can be closed. If not, please reopen.

**Closed by krischer** 2016-01-11 12:57 UTC
Labels: .io.sac, bug, release blocker
