### ISSUE TITLE
SEGY format does not exist in 1.2.2 but works fine in 1.2.1

### ISSUE THREAD

**Issue by erellaz** [obspy/obspy#2832] opened 2021-05-06 18:05 UTC
In version 1.2.1 stream.write(...,format="SEGY",..) works fine.
In version 1.2.2 unfortunately format='SEGY' is not recognized anymore. The error message then proceeds on saying: "available formats", and there is none (no SEGY format, no SU format). So I assume SU format is also broken.

The complete line that works fine in 1.2.1 and not in 1.2.2 is:
stream.write("Shot_"+str(shot_index)+".sgy", format="SEGY", data_encoding=1,byteorder='>')

The complete script is here:
https://github.com/erellaz/SEGY_Wrapper/blob/main/SEGY_wrapper.py

For those who need an immediate fix to this issue, the most simple is to reverse to the last functional version, ie 1.2.1:
pip uninstall obspy
pip install obspy==1.2.1

**Comment by ThomasLecocq** [comment] 2021-05-07 07:04
that's strange, nothing changed in the package since 1.2.1 I think.

**Comment by ThomasLecocq** [comment] 2021-07-27 14:23
I cannot reproduce your issue, so I suspect this is due to a bad installation. Can you confirm you have the same problem in a clean new environment? I did this test:

```python
from obspy import read
import numpy as np
stream = read()
shot_index=0
for tr in stream:
    tr.data = tr.data.astype(np.int32)
stream.write("Shot_"+str(shot_index)+".sgy", format="SEGY", data_encoding=2,byteorder='>')
```
and it works fine.

Closing the issue, feel free to reopen if you confirm it fails in a new environment. Tom

**Closed by ThomasLecocq** 2021-07-27 14:23 UTC
