### ISSUE TITLE
 problem reading MiniSEED file with 512 blank bytes in it

### ISSUE THREAD

**Issue by gposada** [obspy/obspy#1981] opened 2017-11-01 13:51 UTC
Hello obspy developers,

When i execute the command obspy.read() for read a seed file, obspy show an error:

**_InternalMSEEDReadingWarning: readMSEEDBuffer(): Record starting at offset 2813440 is not valid SEED. The rest of the file will not be read.
  warnings.warn(*i)_**

This error is due to what? Is an error of SEED file or of package?

thank you

**Comment by krischer** [comment] 2017-11-01 14:00
I'm fairly certain that this is a wrong SEED file. Just open the file in a hex-editor and have a look at the specified byte position?

Or upload the file somewhere and I can have a look.

**Comment by gposada** [comment] 2017-11-01 14:17
okay, i too think is an error in SEED file. 

You can download the file in [http://siata.gov.co/sismografos/temporal/](url)

Thanks!

**Comment by krischer** [comment] 2017-11-01 14:29
So this file has one 512 byte chunk in it which is completely empty:

![screen shot 2017-11-01 at 15 22 36](https://user-images.githubusercontent.com/800487/32279268-8a0da822-bf18-11e7-99e1-af81c2e655e1.png)

If you remove this chunk the file reads fine. Note that this is different from so called shadow or noise records which we deal with in #1495. These are also empty but they still have at least the sequence number.

It would be fairly straightforward to teach ObsPy how to read this file but I don't really want to do it if its not valid in any case.

@chad-iris Do you have any additional comments/experiences with this?

**Comment by krischer** [comment] 2017-11-27 13:43
I'm reopening this as I'm not sure if this happens more often and we should thus deal with it. Pinging @chad-iris again for a comment ;)

**Comment by megies** [comment] 2017-11-29 19:15
I agree, first thing to do is to find out why and where this happened and how often this might be encountered.

@gposada can you trace the data back to it's origin, i.e. who recorded and with what equipment?

**Comment by gposada** [comment] 2017-11-29 19:32
Hello, the equipment is a RaspberryShake, and the error only happened two times in three months.

I spoke with people from OSOP, they say the error it's due to the Raspberry turns itself off.

**Comment by megies** [comment] 2017-11-30 22:26
OK, given this piece of information, I would argue that this is a bug in the RaspberryShake implementation. If this is an "unclean shutdown" problem, this should be fixed upstream with RaspberryShake. It should not write an all-blank record.

I'll close this as an upstream issue, feel free to reopen, everybody.

**Closed by megies** 2017-11-30 22:26 UTC
Labels: .io.mseed, question

**Comment by chad-iris** [comment] 2017-12-01 00:31
This is definitely not a valid blank or noise record.  In libmseed, these kinds of non-records are optionally skipped using the "skipnotdata" flag in the highest level functions.   Perhaps ObsPy needs something similar for it's readMSEEDBuffer() routine.

**Comment by filefolder** [comment] 2018-01-22 06:50
just searched for this as i'm having the same issue, different digitiser but i feel that the issue is related to the USB thumbdrive it was writing to, i think it was possibly of poor quality or too large or got too hot or who knows.  

regardless, if there's a way to fix this problem in obspy, it would be appreciated. seems like an issue that's going to be recurring with many of these lower cost USB instruments.

**Comment by megies** [comment] 2018-01-22 09:51
> (if someone knew how to do this in bash etc also, that would suffice for me. it's a little beyond my grasp)

@filefolder you should be able to open the file as a bytes buffer and do some manual checking to get rid of all-zero blocks, here's a quick and dirty snippet to get you started..

```python
import io
from obspy import read

reclen = 512

with open('steim2.mseed', 'rb') as fh:
    data = []
    block = fh.read(reclen)
    while block:
        data.append(block)  # put this in if/else for faulty blocks
        block = fh.read(reclen)

data = io.BytesIO(b''.join(data))
data.seek(0)
st = read(data, format='MSEED')
print(st)
´´´

**Comment by krischer** [comment] 2018-01-22 12:27
I implemented this in #2057.

This is a bit different compared to what `libmseed` implements with the `skipnotdata` flag as it only skip chunks of `MINRECLENGTH` that are purely zeros. @chad-iris Do you have any experience if skip non-zero no-data chunks is necessary for some real world cases.

@gposada @filefolder I don't really have your test files (not anymore at least). Could you test this?

**Comment by chad-iris** [comment] 2018-01-22 20:02
>  @chad-iris Do you have any experience if skip non-zero no-data chunks is necessary for some real world cases.

Reading full SEED volumes.  `libmseed` does that by skipping what it does not understand.

**Comment by filefolder** [comment] 2018-01-22 22:03
i can't seem to run the tests (missing libmseed_Linux_64bit_py27.so, seems like my OS is out of date) so until i figure it out here's my file and the error

[test.mseed.gz](https://github.com/obspy/obspy/files/1653691/test.mseed.gz)

```
In [2]: obspy.read("test.mseed")
/usr/local/lib/python2.7/dist-packages/obspy-1.1.0.post0+112.g32feb03f78.dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/io/mseed/headers.py:828: InternalMSEEDWarning: NZ_RBAZ_10_Z_D: Warning: Number of blockettes in fixed header (2) does not match the number parsed (1)
  warnings.warn(_w, InternalMSEEDWarning)
/usr/local/lib/python2.7/dist-packages/obspy-1.1.0.post0+112.g32feb03f78.dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/io/mseed/headers.py:828: InternalMSEEDWarning: readMSEEDBuffer(): Record starting at offset 1114112 is not valid SEED. The rest of the file will not be read.
  warnings.warn(_w, InternalMSEEDWarning)
Out[2]: 
1 Trace(s) in Stream:
NZ.RBAZ.10.Z | 2017-12-18T00:00:00.000000Z - 2017-12-18T00:44:10.345000Z | 200.0 Hz, 530070 samples


```

**Comment by krischer** [comment] 2018-01-23 10:33
@chad-iris Ah okay. We explicitly handle full SEED volumes but with the latest changes we additionally skip any data blocks we don't understand.

@filefolder Yea this file really has a tone of issues. A side effect of #2057 is unfortunately that ObsPy is no longer able to read the file at all as later in the file it encounters errors it cannot recover from. I guess this is an acceptable trade off and users would have to manually deal with such files. Your test files raises hundreds of warnings and reading then finally fails with

```python
InternalMSEEDError: Encountered 8 error(s) during a call to readMSEEDBuffer():
msr_unpack_data(OZ_RbAZ"_14__D): only decoded 1408 samples of 10168 expected
msr_unpack(Oz_RBAZ"_14__D): Unknown blockette length for type 43950
msr_unpack_data(Oz_RBAZ"_14__D): only decoded 1824 samples of 2010 expected
msr_unpack_data(NZ_RBAZ_10_Z_D): only decoded 1918 samples of 1948 expected
msr_unpack_data(NZ_RBAZ_10_Z_D): only decoded 1975 samples of 2000 expected
msr_unpack_data(NZ_RBAZ_10_Z_D): only decoded 1942 samples of 1952 expected
msr_unpack(LZ_RBaZ_10_Z_D): Unknown blockette length for type 5096
msr_unpack_data(LZ_RBaZ_10_Z_D): only decoded 1929 samples of 18334 expected
```
