### ISSUE TITLE
Update libmseed

### ISSUE THREAD

**Issue by baerbock** [obspy/obspy#2514] opened 2019-12-11 20:14 UTC
It's time to update https://github.com/iris-edu/libmseed . This would fix recent compilation errors due to `off_t`.

→ [Changelog](https://github.com/iris-edu/libmseed/blob/master/ChangeLog)

**Comment by krischer** [comment] 2019-12-11 20:43
Duplicate of #2376 

libmseed 3 has a fundamentally different API and also supports a new version of MiniSEED. The current libmseed we bind is such an integral part of ObsPy that we could only change it by being really careful and with a lot of testing. That being said we'll def do it at one point.

**Closed by krischer** 2019-12-11 20:43 UTC

**Comment by megies** [comment] 2019-12-12 00:00
CC @chad-iris

**Comment by chad-iris** [comment] 2019-12-16 17:43
FWIW, I agree with @krischer.  The latest libmseed is a relatively large change (major version) and should be done with care.  The good news is that API has been added that allows data samples to be decoded to caller-supplied memory buffers, potentially faster and simpler than the current pattern ObsPy uses.  I would be willing to help as much as I can with libmseed 3 integration, but am not very familiar with the internal OsbPy structure construction needed passing pre-allocated buffers.
