### ISSUE TITLE
A problem with Obspy on Raspbery PI -- mseed write -- solved (ish)

### ISSUE THREAD

**Issue by starfishprime101** [obspy/obspy#2083] opened 2018-03-01 22:57 UTC
Hi
I have had problems running obspy (python3) on a raspberry pi leading to error messages such as
ValueError: /usr/lib/python3/dist-packages/obspy/core/util/../../lib/libmseed_Linux_32bit_py34.cpython-34m.so: undefined symbol: LM_SIZEOF_OFF_T. Here I am trying to write in mseed format

This can be solved by renaming all the files in /usr/lib/python3/dist-packages/obspy/lib/ to omit the "-arm-linux-gnueabihf" element of their filenames

i.e. 
"sudo cp /usr/lib/python3/dist-packages/obspy/lib/libmseed_Linux_32bit_py34.cpython-34m-arm-linux-gnueabihf.so                                                                                                                                           /usr/lib/python3/dist-packages/obspy/lib/libmseed_Linux_32bit_py34.cpython-34m.so "
 

and so on for the others in the directory

Trust this is of some help

Ian

**Comment by megies** [comment] 2018-03-02 09:47
I trust it you installed the current deb packages from our apt repo? Are you on Raspbian? What version?

**Comment by starfishprime101** [comment] 2018-03-02 11:22
Good point about versions

I am running Jessie (debian)  8 kept fully up to date on stable. Obspy is version 3, agin kept up to date with apt-get.

I had to do a similar thing last summer which may have been a previous version???

**Comment by megies** [comment] 2018-03-02 12:07
Hrrmmm.. I can confirm this problem. Strange how this did not surface during packaging since it also involves running the tests on the built packages..

**Comment by krischer** [comment] 2018-03-02 12:10
Does this file exist in the distribution prior to renaming? ` /usr/lib/python3/dist-packages/obspy/core/util/../../lib/libmseed_Linux_32bit_py34.cpython-34m.so`

**Comment by megies** [comment] 2018-03-02 12:21
Nah, I have a shell script that renames built libs to match our naming standards. During deb packaging the Debian canonical naming is applied and I have to rename all these files.

**Comment by krischer** [comment] 2018-03-02 13:25
Where does this come from then? If ObsPy could not find the shared library it would raise a different error but it complains about undefined symbols which might mean its an old version of the library. Do you think its possible that this is some kind of remnant from a previous obspy installation?

**Comment by megies** [comment] 2018-03-02 13:34
Oh, overlooked that detail.. but for me locally on a clean ARM docker image it was a normal `ImportError: Could not load shared library "libmseed_Linux_32bit_py34.cpython-34m.so".` so yeah, I guess it was some remnant from an old local monkey-patch renaming for the OP..

**Comment by krischer** [comment] 2018-03-02 13:39
I see. We could also make the `load_lib()` function a bit more general and fallback to loading libraries with different things at the end (e.g. `libmseed_*.so`) if it cannot find the exact name for whatever reason.

**Comment by megies** [comment] 2018-03-02 13:43
Yeah, although that just might introduce different problems that might then even be harder to debug due to being slightly non-deterministic (if we do wildcard matching).

**Comment by krischer** [comment] 2018-03-02 14:20
True. I wonder why it chooses a different name during compilation and during loading. We use the same functions for both: https://github.com/obspy/obspy/blob/master/obspy/core/util/libnames.py

Can you debug this on your raspberry pi?

**Comment by megies** [comment] 2018-03-02 14:28
There's a lot of magic during deb packaging, i think it's just renaming `.so` files using regex, dunno. Not worth fighting it, I think. If you got too much time you can debug it in docker.. ;-P

**Comment by krischer** [comment] 2018-03-02 15:58
Haha - don't worry - I don't intend to mess with the Debian packaging.

**Comment by megies** [comment] 2018-03-05 16:39
I uploaded new packages for ARM Raspbian 8 "Jessie" that fix the problem. Will do Raspbian 9 stretch tomorrow.

**Comment by megies** [comment] 2018-03-07 09:39
@krischer btw see d30548c351 for more info on this topic

**Comment by megies** [comment] 2018-03-07 12:50
Oh my, it gets even more confusing..
 - on Debian up to 8 (jessie), `sysconfig` has plain extension suffix (`sysconfig.get_config_var("EXT_SUFFIX")`: `'.cpython-34m.so'`) but setuptools is patched to rename built extensions with the more detailed extension suffix (`'.cpython-34m-arm-linux-gnueabihf.so'`)
 - on Debian 9 (stretch; and presumably the next versions as well??) `sysconfig` already has the more complex extension suffix (`'.cpython-35m-arm-linux-gnueabihf.so'`), setuptools is still patched but not doing anything because the expected suffix is already there, so we must not apply the renaming in that case..

In any case, the problem described by the OP was only affecting Raspbian 8 "jessie" and not 9 "stretch", so the problem is fixed now.

**Closed by megies** 2018-03-07 12:50 UTC
Labels: DEB, bug, packaging

**Comment by starfishprime101** [comment] 2018-03-18 17:14
Hi Folks

thanks for your work on this. Seems fixed, I have tested it on Raspberry PI running Jessie and Stretch - everything OK after reinstalling then reinstalling ObsPy

Cheers

Ian
