### ISSUE TITLE
travelTimePlot() function in obspy version 1.0.1 deprecated?

### ISSUE THREAD

**Issue by pjkoelemeijer** [obspy/obspy#1501] opened 2016-08-05 14:03 UTC
Using Obspy 1.0.1, installed through Anaconda 4.1.1 on Linux 64-bit. 
Trying to duplicate example 29.1 in the obspy tutorials: 
https://docs.obspy.org/tutorial/code_snippets/travel_time.html
One receives the warning: 
The travelTimePlot() function is deprecated. Please use the obspy.taup.TauPyModel class directly.

However, the obspy.taup.TauPyModel class does not seem to have a plot function in the same way, only a possibility to calculate travel times. For student teaching purposes, it would be great to have this function still. And it would also be nice to have an option for model PREM. 

Many thanks!

**Comment by megies** [comment] 2017-10-05 13:24
Duplicate of #1330

**Closed** 2017-10-05 18:43 UTC
Labels: .taup, duplicate
