### ISSUE TITLE
Error with writing SEG-Y file, SEG-Y_r2.0

### ISSUE THREAD

**Issue by AriesChen-UPC** [obspy/obspy#3239] opened 2022-12-13 03:19 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

There is an error occured when writing data to segy file as follows:
```
ValueError: Can not write traces with more than 32767 samples (trace at index 0):
```
Does the obspy support the SEG-Y_r2.0 ?

### Code to Reproduce

```python
import numpy as np
from obspy import Trace, Stream
import sys
from obspy.io.segy.segy import SEGYTraceHeader, SEGYBinaryFileHeader
from obspy.core import AttribDict
stream = Stream()
for i in range(3):
    trace=Trace(data=np.array(range(32768),dtype='float32'))
    trace.stats.delta = 0.000125
    if not hasattr(trace.stats,'segy.trace_header'):
        trace.stats.segy={}
    trace.stats.segy.trace_header = SEGYTraceHeader()
    stream.append(trace)
stream.stats = AttribDict()
stream.stats.binary_file_header = SEGYBinaryFileHeader()
stream.stats.binary_file_header.number_of_data_traces_per_ensemble=1
stream.write("migrated_infilled.sgy", format="SEGY", data_encoding=1,
             byteorder=sys.byteorder)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-9221bd5e6983>", line 17, in <module>
    stream.write("migrated_infilled.sgy", format="SEGY", data_encoding=1,
  File "E:\anaconda3\lib\site-packages\obspy\core\stream.py", line 1456, in write
    write_format(self, filename, **kwargs)
  File "E:\anaconda3\lib\site-packages\obspy\io\segy\core.py", line 276, in _write_segy
    raise ValueError(msg.format(MAX_NUMBER_OF_SAMPLES, i, tr))
ValueError: Can not write traces with more than 32767 samples (trace at index 0):
Seq. No. in line:    0 | 1970-01-01T00:00:00.000000Z - 1970-01-01T00:00:04.095875Z | 8000.0 Hz, 32768 samples
```

### ObsPy Version?

1.3.0

### Operating System?

Windows

### Python Version?

Python 3.9.7

### Installation Method?

pip

**Comment by ThomasLecocq** [comment] 2022-12-13 06:40
duplicate of many other issues. You have to manually cut your stream into shorter traces to be able to write segy with obspy, or use an external package. SEGY rev2 is not supported

Search Issues: https://github.com/obspy/obspy/issues?q=32767+

**Closed by ThomasLecocq** 2022-12-13 06:40 UTC
Labels: bug-unconfirmed

**Comment by AriesChen-UPC** [comment] 2022-12-14 00:38
Thank you! In the future, I will check more carefully for repetitive questions before asking them.

**Comment by megies** [comment] 2022-12-15 08:17
> ```python
> ValueError: Can not write traces with more than 32767 samples (trace at index 0):
> Seq. No. in line:    0 | 1970-01-01T00:00:00.000000Z - 1970-01-01T00:00:04.095875Z | 8000.0 Hz, 32768 samples
> ```

You might also just cut off last sample, if the message we print there isn't faulty
