### ISSUE TITLE
Floating point errors introduced to delta field when reading/writing .sac files

### ISSUE THREAD

**Issue by El-minadero** [obspy/obspy#2402] opened 2019-05-21 21:30 UTC
obspy version: 1.1.1
python version: 3.7.3
platform: Linux Eementary OS, Juno 5.0
installed Obspy via conda

Obspy introduces what looks like floating point errors to the time delta field when reading/writing sac files. For small traces this hasn't been a issue, but under high sampling rate/long times, this introduces inconsistent npts calculations when using the delta+calculated endtime to query sub traces.
```python

from obspy import read
from obspy.core import UTCDateTime
from obspy.core.trace import Stats
from obspy.core import Trace
import numpy as np

def create_trace(sampling_rate=250.0):
    data  = np.random.normal(0,1,size=(int(sampling_rate*60*60*24)))
    trace = Trace(data=data,header={'sampling_rate':sampling_rate,
                          'starttime':UTCDateTime(0)})
    return trace

file='s.sac'
trace = create_trace()
print(trace.stats['delta'])
trace.write(file,format='SAC')
st    = read(file)
print(st[0].stats['delta'])

```
Output:
```
0.004
0.00400000024414064
```

Edit: Clarified the npts error was not directly from reading in .sac files.

**Comment by krischer** [comment] 2019-05-21 22:17
This is a consequence of SAC storing the sample interval as a single precision float, and going back and forth between sampling rate and sampling interval can reproduce the number.

```python
In [16]: 1.0 / np.float32(np.float32(1.0) / np.float32(np.float64(np.float32(1.0) / np.float32(250.0))))
Out[16]: 0.00400000024414064
```

I'm not sure there is a lot that can be done here without a crazy amount of effort, as floating point inaccuracies are just a fact of dealing with computers. Even this simplistic example is not fully accurate:

```python
np.float64(np.float32(1.0 / 250.0))
```

I don't understand how this would cause `npts` accuracy issues as you claim. Do you mean end time differences? I agree here but you would have to accumulate a very large number of samples for this to matter in practice. Also note that our `UTCDateTime` object has a built-in precision and any comparison operators on it will honor it (It defaults to 1E-6 seconds) - real world clocks are also not fully accurate.

**Comment by kaspervanwijk** [comment] 2019-05-21 22:23
I can see why delta has to be a float, of course, but can npts just be an
integer? Or am I naive to think npts of a trace is always an integer value?

**Comment by El-minadero** [comment] 2019-05-21 22:29
@krischer I suppose It is inaccurate to claim inconsistent npts calculations, but rather inconsistent npts calculations when querying for a trace subset using npts, delta, start, and end times. I used [obsplus](https://github.com/niosh-mining/obsplus) to retrieve 5 minute sub traces from a larger dataset, with the result that many of the returned traces had npts that were not the same (off by 1-3).  Since obsplus uses the calculated end times and sampling rate to determine where to slice the data, I assume the error I observed arose from the floating point error calculations in reading the sac headers.

Is there not a way to say, round to the nearest nth decimal in the .sac read routines?

**Comment by krischer** [comment] 2019-05-21 22:29
> I can see why delta has to be a float, of course, but can npts just be an integer? Or am I naive to think npts of a trace is always an integer value?

`npts` is of course an integer. None of my computations above involve the number of samples. But in any case: As soon as `npts` interacts with a floating point number it will be upcast to one.

**Comment by krischer** [comment] 2019-05-21 22:45
> @krischer I suppose It is inaccurate to claim inconsistent npts calculations, but rather inconsistent npts calculations when querying for a trace subset using npts, delta, start, and end times. I used [obsplus](https://github.com/niosh-mining/obsplus) to retrieve 5 minute sub traces from a larger dataset, with the result that many of the returned traces had npts that were not the same (off by 1-3). Since obsplus uses the calculated end times and sampling rate to determine where to slice the data, I assume the error I observed arose from the floating point error calculations in reading the sac headers.
> 
> Is there not a way to say, round to the nearest nth decimal in the .sac read routines?

I guess you could do it yourself if you are confident that it is applicable to your data. We don't want to do this on the ObsPy site as for example a sampling rate of 3 Hz would otherwise be represented pretty badly as a 0.333 second time interval.

Unfortunately accurately trimming data based on  start time and sample spacing is a surprisingly hard problem and there are only two halfway decent solutions I'm aware of:

(1) double precision all the way. Unfortunately not possible in most data format but for example MiniSEED has a clever way to store accurate sampling rate.
(2) Having intermediate time stamps (also something MiniSEED does) and just don't operate on very long traces.

In a different context I once did the following experiment:

```python
from decimal import Decimal as D
import numpy as np

starttime_in_ns = 124734934578
# Awkward sampling rate to force floating point errors.
sampling_rate_in_sec = 201.12345678
samples = 4294967295 // 2

endtime_in_ns_d = \
    D(starttime_in_ns) + D("1000000000") / D(sampling_rate_in_sec) * D(samples)
# Use a single precision sampling rate.
endtime_in_ns = \
    starttime_in_ns + 1000000000 / np.float32(sampling_rate_in_sec) * samples

print("Endtime in ns - accurate:      ", int(endtime_in_ns_d))
print("Endtime in ns - floating point:", int(endtime_in_ns))
diff = abs(int(endtime_in_ns_d) - int(endtime_in_ns))
print("Difference in ns:              ", diff)
print("Difference as a factor of dt:  ",
      (diff / 1E9) / (1.0 / sampling_rate_in_sec))
```

```
Endtime in ns - accurate:       10677564757999798
Endtime in ns - floating point: 10677564647452358
Difference in ns:               110547440
Difference as a factor of dt:   22.233683270979643
```

Changing the single precision sampling rate to a double precision one completely eliminates the error. In practice this is hard to do because you effectively limit yourself to a 32 bit sampling rate if you serialize to 32 bit at one point in the chain. Thus my advice would be to store in a different format that can store a 64 bit sampling rate.

**Comment by El-minadero** [comment] 2019-05-21 22:55
@krischer Hm. Well in that case the fix does not seem appropriate for ObsPy, and the error is probably a consequence of my organization's workflow.

**Comment by d-chambers** [comment] 2019-05-28 05:04
@El-minadero, 
Yes probably nothing to do on the obspy end. Closing for now, re-open if you think there is more to be done/discussed.

**Closed by d-chambers** 2019-05-28 05:04 UTC
