### ISSUE TITLE
Problems to load npz files

### ISSUE THREAD

**Issue by edwarzambrano** [obspy/obspy#2417] opened 2019-06-22 00:38 UTC
hello everyone

when i run ppsd = PPSD.load_npz("npz_name), I get the following
```
File "/home/usuario/anaconda3/envs/obspy1/lib/python3.7/site-packages/obspy/signal/spectral_estimation.py", line 1257, in load_npz
return _load(data)
File "/home/usuario/anaconda3/envs/obspy1/lib/python3.7/site-packages/obspy/signal/spectral_estimation.py", line 1242, in load
data = data[key]
File "/home/usuario/anaconda3/envs/obspy1/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in getitem
pickle_kwargs=self.pickle_kwargs)
File "/home/usuario/anaconda3/envs/obspy1/lib/python3.7/site-packages/numpy/lib/format.py", line 696, in read_array
raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```
Obspy version 1.1.1
Python version 3.7.3
Platform Linux
Obspy and Python installed via Anaconda

**Comment by d-chambers** [comment] 2019-06-22 15:15
Hey @edwarzambrano, thanks for reporting this. It appears to be a duplicate of #2409 so watch that issue for resolution. Feel free to reopen if you disagree.

**Closed by d-chambers** 2019-06-22 15:15 UTC

**Comment by megies** [comment] 2019-06-24 12:33
@edwarzambrano for now the easiest solution for you would be to downgrade numpy to <1.16
