### ISSUE TITLE
Incompatibility with scipy1.9

### ISSUE THREAD

**Issue by zhong-yy** [obspy/obspy#3129] opened 2022-08-17 03:15 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

An error is raised when using resample(). It seems due to the incompatibility with scipy 1.9.

scipy 1.9
numpy 1.23.2
obspy 1.3.0

### Code to Reproduce

```python
from obspy import read
st=read()
st.resample(50)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2214, in get_window
    beta = float(window)
ValueError: could not convert string to float: 'hanning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2232, in get_window
    winfunc = _win_equiv[winstr]
KeyError: 'hanning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyy/test.py", line 4, in <module>
    st.resample(50)
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/obspy/core/stream.py", line 2351, in resample
    tr.resample(sampling_rate, window=window,
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/obspy/core/util/decorator.py", line 237, in skip_if_no_data
    return func(*args, **kwargs)
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/obspy/core/trace.py", line 282, in _add_processing_info
    result = func(*args, **kwargs)
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/obspy/core/trace.py", line 1744, in resample
    large_w = np.fft.ifftshift(get_window(window,
  File "/home/zyy/miniconda3/envs/obspy/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2234, in get_window
    raise ValueError("Unknown window type.") from e
ValueError: Unknown window type.
```

### ObsPy Version?

1.3.0

### Operating System?

Ubuntu

### Python Version?

3.10.5

### Installation Method?

conda

**Comment by calum-chamberlain** [comment] 2022-08-17 04:50
Duplicate of #3116 - please see that issue and related PR for solution. Thanks for reporting.

**Closed by calum-chamberlain** 2022-08-17 04:50 UTC
Labels: bug-unconfirmed

**Comment by megies** [comment] 2022-08-17 14:00
..and please not just tick that box "I searched existing issues" but also do it :zany_face: :zany_face:
