### ISSUE TITLE
Python3.5 installation issue

### ISSUE THREAD

**Issue by damb** [obspy/obspy#2525] opened 2019-12-23 14:13 UTC
Hi devs,

apparently there is an issue while installing `obspy==1.1.1` under Python **3.5**. The installation is performed as follows:

```bash
$ virtualenv -p $(which python3.5) venv
$ . venv/bin/activate
$ python --version
Python 3.5.9
$ pip install numpy
$ pip install -v obspy

[...]

ERROR: Command errored out with exit status 1: /home/damb/tmp/venv/bin/python3.5 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e6idm51i/obspy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e6idm51i/obspy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lcrq8jjq/install-record.txt --single-version-externally-managed --compile --install-headers /home/damb/tmp/venv/include/site/python3.5/obspy Check the logs for full command output.
```

Apparently it fails while compiling `libmseed`. Detailed installation logs are attached ([obspy.install.log](https://github.com/obspy/obspy/files/3995203/obspy.install.log)).

```
$ pip freeze
certifi==2019.11.28
chardet==3.0.4
cycler==0.10.0
decorator==4.4.1
future==0.18.2
idna==2.8
kiwisolver==1.1.0
lxml==4.4.2
matplotlib==3.0.3
numpy==1.18.0
pkg-resources==0.0.0
pyparsing==2.4.5
python-dateutil==2.8.1
requests==2.22.0
scipy==1.4.1
six==1.13.0
SQLAlchemy==1.3.12
urllib3==1.25.7
```

```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I run Linux:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Is this a known issue? Do you need any further details? `obspy==1.1.0` seems to install smoothly.

Thanks in advance.

**Comment by megies** [comment] 2019-12-25 06:29
I don't see any change from 1.1.0 to 1.1.1 in io/mseed C sources that should cause compilation issues. This is the only change in C what I see:

https://github.com/obspy/obspy/compare/1.1.0...1.1.1?expand=1#diff-c02ba4288b08f84fecc29345382c80c1

Looks like a compiler setup problem, but don't really know.

**Comment by megies** [comment] 2019-12-25 06:31
Any particular reason to use an EOL Python?

**Comment by batearedcollie** [comment] 2019-12-28 18:04
Getting the same error installing Obspy as part of building a Docker image, version 1.1.0 builds/installs ok

To reproduce:

**gcc --version**
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**python3 --version**
Python 3.6.9

**Dockerfile**
FROM ubuntu:18.04 
RUN apt-get update && \
    apt-get install -y --no-install-recommends  \
    python3-dev libgomp1 libxml2 python3-pip python3-setuptools build-essential libfftw3-dev && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install numpy>=1.15.1 sh>=1.12.14 pytz>=2019.2 && \
    python3 -m pip install  obspy>=1.1.1

**Comment by damb** [comment] 2020-01-03 09:48
> Any particular reason to use an EOL Python?

Aren't all Python versions coming along with an EOL (see also: [here](https://devguide.python.org/#status-of-python-branches))?

**Comment by damb** [comment] 2020-01-03 10:52
Originally the issue occurred while I was trying to build a Docker image (based on Ubuntu LTS 16.04 which comes along with Python3.5 as the default Python3 version). Then I figured out that the same exception was raised while installing `obspy==1.1.1` into an empty virtual environment on Ubuntu 18.04 LTS with Python3.5.

I'll try to switch to a more recent Ubuntu 18.04 LTS based image and check if this works (with Python3.6). Maybe I'm more lucky than @batearedcollie.

**Comment by damb** [comment] 2020-01-03 11:49
> I'll try to switch to a more recent Ubuntu 18.04 LTS based image and check if this works (with Python3.6). Maybe I'm more lucky than @batearedcollie.

@batearedcollie, same error for me.

**Comment by damb** [comment] 2020-01-03 12:40
Here the detailed installation logs when trying to install with Python **3.6** (OS and gcc version are still the same): [obspy.install.log](https://github.com/obspy/obspy/files/4019104/obspy.install.log)
```
$ python3.6 -m venv venv
$ . venv/bin/activate
$ python --version
Python 3.6.9
$ pip install --no-cache-dir numpy
[...]
Successfully installed numpy-1.18.0
$ pip install --no-cache-dir --log obspy.install.log obspy
[...]
Running setup.py install for obspy ... error
Command "/home/damb/tmp/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-emzx3glr/obspy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-j8i06dtb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/damb/tmp/venv/include/site/python3.6/obspy" failed with error code 1 in /tmp/pip-build-emzx3glr/obspy/
```

**Comment by ThomasLecocq** [comment] 2020-03-13 13:47
@damb did you manage to get this working ? any progress on this ?

**Comment by damb** [comment] 2020-03-13 13:56
@ThomasLecocq, nope. The facilities I needed where provided by `obspy==1.1.0`, anyway. Besides, I was hoping to switch immediately to `obspy==`1.2.x`.

I know this doesn't help you further. Sorry.

**Comment by megies** [comment] 2020-03-13 14:25
Closing. Please reopen if there's a problem again

**Closed by megies** 2020-03-13 14:25 UTC
Labels: installation

**Comment by damb** [comment] 2020-03-14 09:09
I just gave it once again a try. Note that I used Python **3.6** under which the installation previously failed, too. To recall, the setup:

```
$ python3 --version
Python 3.6.9
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I could install `obspy==1.1.1` whithout any problems. Here's the freeze:

```
$ pip freeze
certifi==2019.11.28
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
future==0.18.2
idna==2.9
kiwisolver==1.1.0
lxml==4.5.0
matplotlib==3.2.0
numpy==1.18.1
obspy==1.1.1
pkg-resources==0.0.0
pyparsing==2.4.6
python-dateutil==2.8.1
requests==2.23.0
scipy==1.4.1
six==1.14.0
SQLAlchemy==1.3.15
urllib3==1.25.8
```

Moving forward to `Ubuntu 18.04.4 LTS` solved the problem for me. Thanks to everybody helping with this.
