### ISSUE TITLE
read_inventory() fails when xml comment present

### ISSUE THREAD

**Issue by mikehagerty** [obspy/obspy#2884] opened 2021-10-06 18:24 UTC
obspy v1.2.2 installed via conda, mac os 10.14.6

The comment on the 2nd line below kills read_inventory():
```
<fsx:NormalizationFrequency>1.000000000000E+00</fsx:NormalizationFrequency>
<!-- MTH: added this zero + fixed the pole location of DC 1mHz removal filter -->
<fsx:Zero number="0">
```

I believe that's the correct XML comment syntax (?) so would not expect it to fail.
Thanks!

  File "<decorator-gen-49>", line 2, in read_inventory
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/inventory/inventory.py", line 89, in read_inventory
    **kwargs)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/util/base.py", line 702, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-50>", line 2, in _read
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/inventory/inventory.py", line 98, in _read
    **kwargs)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/core/util/base.py", line 470, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 186, in _read_stationxml
    _read_extra(root, inv)  # read extra tags from root element
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 1679, in _read_extra
    extra = _read_element(prefix, ns, el, extra)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 1654, in _read_element
    _read_element(prefix, ns, nested_el, extra[name].value)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 1654, in _read_element
    _read_element(prefix, ns, nested_el, extra[name].value)
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 1654, in _read_element
    _read_element(prefix, ns, nested_el, extra[name].value)
  [Previous line repeated 1 more time]
  File "/Users/mth/mth/miniconda3/lib/python3.6/site-packages/obspy/io/stationxml/core.py", line 1647, in _read_element
    _, name = element.tag.split("}")
AttributeError: 'cython_function_or_method' object has no attribute 'split'

**Comment by ThomasLecocq** [comment] 2022-01-05 13:09
Hi @mikehagerty could you attach a sample XML file to test? Thanks!

**Comment by megies** [comment] 2022-03-10 08:38
@mikehagerty I can't reproduce this either and to me it doesn't look like that comment is to blame but rather something going on in some nested custom non-StationXML tags, but it's impossible to tell from the information we have. I'm closing this as we can do nothing about it unless we get more info. Please feel free to reopen with more information.

**Closed by megies** 2022-03-10 08:38 UTC
