### ISSUE TITLE
Data length from Stream.trim differ from other trim/slice methods

### ISSUE THREAD

**Issue by GentleMin** [obspy/obspy#2608] opened 2020-05-02 14:19 UTC
I am using obspy 1.2.1 on windows. I have encountered a rather weird situation using `stream.trim` with `stream.slice`, `trace.trim` and `trace.slice`. Not sure if it is intended, but the 1st methods seems to be behaving slightly different from the others. Basically, in the following instance, `stream.trim` yields a 1-point shorter array than the others, even if `nearest_sample` is always  used.
This is the original stream.
```
ipdb> print(st_b)
3 Trace(s) in Stream:
BD.BD09..HLE | 2017-05-24T09:10:14.284121Z - 2017-05-24T12:10:14.274121Z | 100.0 Hz, 1080000 samples
BD.BD09..HLN | 2017-05-24T09:10:14.284121Z - 2017-05-24T12:10:14.274121Z | 100.0 Hz, 1080000 samples
BD.BD09..HLZ | 2017-05-24T09:10:14.284121Z - 2017-05-24T12:10:14.274121Z | 100.0 Hz, 1080000 samples
```

Now `stream.slice` is used. The result has 6801 sample points.
```
ipdb> st_b_2 = st_b.slice(starttime=reftime + float(move[0]), endtime=reftime + float(move[1]), nearest_sample=True)

ipdb> print(st_b_2)
3 Trace(s) in Stream:
BD.BD09..HLE | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
BD.BD09..HLN | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
BD.BD09..HLZ | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
```

Next I tried `trace.trim` on the result. There is no difference, and the length remains 6801.
```
ipdb> st_b_2[0].trim(starttime=reftime + float(move[0]), endtime=reftime + float(move[1]), nearest_sample=True)

ipdb> print(st_b_2)
3 Trace(s) in Stream:
BD.BD09..HLE | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
BD.BD09..HLN | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
BD.BD09..HLZ | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.124121Z | 100.0 Hz, 6801 samples
```

Things are different if I use `stream.trim`. Both `st_b` and `st_b_2` are cut to 6800 points.
```
ipdb> st_b.trim(starttime=reftime + float(move[0]), endtime=reftime + float(move[1]), nearest_sample=True)

ipdb> print(st_b)
3 Trace(s) in Stream:
BD.BD09..HLE | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples
BD.BD09..HLN | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples
BD.BD09..HLZ | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples

ipdb> st_b_2.trim(starttime=reftime + float(move[0]), endtime=reftime + float(move[1]), nearest_sample=True)

ipdb> print(st_b_2)
3 Trace(s) in Stream:
BD.BD09..HLE | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples
BD.BD09..HLN | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples
BD.BD09..HLZ | 2017-05-24T09:16:52.124121Z - 2017-05-24T09:18:00.114121Z | 100.0 Hz, 6800 samples
```

It is probably concerned with rounding, and it occurs very rarely. I have trimmed thousands of traces, which all yield exactly the same npts. This is the only weird exception I have found.

**Comment by trichter** [comment] 2020-05-02 21:19
Interesting. Can you please also post the values of `reftime` and `move` variables?

The different behaviour is probably not intended. Stream.trim and Stream.slice should give the same result. The following code block only appears in Stream.trim and not in the other methods. I don't really know why this code is necessary, similar checks exist in Trace._ltrim/_rtrim. I remember I wondered before.

```
        if nearest_sample:
            tr = self.traces[0]
            try:
                if starttime is not None:
                    delta = compatibility.round_away(
                        (starttime - tr.stats.starttime) *
                        tr.stats.sampling_rate)
                    starttime = tr.stats.starttime + delta * tr.stats.delta
                if endtime is not None:
                    delta = compatibility.round_away(
                        (endtime - tr.stats.endtime) * tr.stats.sampling_rate)
                    # delta is negative!
                    endtime = tr.stats.endtime + delta * tr.stats.delta
            except TypeError:
                msg = ('starttime and endtime must be UTCDateTime objects '
                       'or None for this call to Stream.trim()')
                raise TypeError(msg)
```

**Comment by megies** [comment] 2020-05-05 09:50
> The different behaviour is probably not intended. Stream.trim and Stream.slice should give the same result

I agree :+1:

**Comment by trichter** [comment] 2020-05-05 12:11
Minimal reproducing example:

```py
from obspy import read

st = read()
utc = st[0].stats.starttime
dt = 1.045

print(utc+dt)
print(st.copy().trim(None, utc+dt)[0])
print(st.slice(None, utc+dt)[0])
print(len(st.copy().trim(None, utc+dt)[0]) == len(st.slice(None, utc+dt)[0]))
```

outputs

```
2009-08-24T00:20:04.045000Z
BW.RJOB..EHZ | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:04.040000Z | 100.0 Hz, 105 samples
BW.RJOB..EHZ | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:04.050000Z | 100.0 Hz, 106 samples
False
```

Maybe we can fix this by simply removing the earlier reproduced code block?

**Comment by zhong-yy** [comment] 2022-06-08 15:31
Hi, I have the same problem. Here is another example.

```python
# Prepare data
from obspy import read, UTCDateTime
from obspy.clients.fdsn import Client
client=Client("IRIS")
stt=UTCDateTime("2006-06-25T12:08:57.579400Z")
edt=stt+128
st=client.get_waveforms(starttime=stt,endtime=edt,network="AV",station="ACH",location="--",channel="EH*")
st.resample(100) # If I comment out this, all the following 3 tests give the same results
print(st)
dt=st[0].stats.delta
```

```python
# Test 1: using slice(), no problem
new_stt=UTCDateTime("2006-06-25T12:09:39.444400Z")-0.005
st_trimed=st.copy().slice(starttime=new_stt,endtime=new_stt+3000*dt)
print(st_trimed)

#3 Trace(s) in Stream:
#AV.ACH..EHE | 2006-06-25T12:09:39.440700Z - 2006-06-25T12:10:09.440700Z | 100.0 Hz, 3001 samples
#AV.ACH..EHN | 2006-06-25T12:09:39.439400Z - 2006-06-25T12:10:09.439400Z | 100.0 Hz, 3001 samples
#AV.ACH..EHZ | 2006-06-25T12:09:39.440000Z - 2006-06-25T12:10:09.440000Z | 100.0 Hz, 3001 samples
```

```python
# Test2: using trim(), problematic ()
new_stt=UTCDateTime("2006-06-25T12:09:39.444400Z")-0.005
st_trimed=st.copy().trim(starttime=new_stt,endtime=new_stt+3000*dt)
print(st_trimed)

#3 Trace(s) in Stream:
#AV.ACH..EHE | 2006-06-25T12:09:39.440700Z - 2006-06-25T12:10:09.430700Z | 100.0 Hz, 3000 samples
#AV.ACH..EHN | 2006-06-25T12:09:39.449400Z - 2006-06-25T12:10:09.439400Z | 100.0 Hz, 3000 samples
#AV.ACH..EHZ | 2006-06-25T12:09:39.440000Z - 2006-06-25T12:10:09.430000Z | 100.0 Hz, 3000 samples
```

```python
# Test 3: using trim() with another starttime, it is OK
new_stt=UTCDateTime("2006-06-25T12:09:39.444400Z")
st_trimed=st.copy().trim(starttime=new_stt,endtime=new_stt+3000*dt)
print(st_trimed)

#3 Trace(s) in Stream:
#AV.ACH..EHE | 2006-06-25T12:09:39.440700Z - 2006-06-25T12:10:09.440700Z | 100.0 Hz, 3001 samples
#AV.ACH..EHN | 2006-06-25T12:09:39.449400Z - 2006-06-25T12:10:09.449400Z | 100.0 Hz, 3001 samples
#AV.ACH..EHZ | 2006-06-25T12:09:39.440000Z - 2006-06-25T12:10:09.440000Z | 100.0 Hz, 3001 samples
```

In the second test, among the three channels, only the EHN is trimmed at an unexpected time.

**Comment by trichter** [comment] 2022-09-23 15:50
This issue should be fixed in the linked PR.

**Closed by trichter** 2022-09-23 15:50 UTC
Labels: .core
