### ISSUE TITLE
Error initializing NCEDC client

### ISSUE THREAD

**Issue by emthompson-usgs** [obspy/obspy#3134] opened 2022-09-02 17:02 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Looks like there is a problem creating an FDSN client for the NCEDC. Please see the attached code and traceback. It is unclear to me if this is an obspy issue or an NCEDC issue and could use some help on how to figure that out. 

### Code to Reproduce

```python
from obspy.clients.fdsn import Client
client = Client("NCEDC", debug=True)
```

### Error Traceback

```Python traceback
In [1]: from obspy.clients.fdsn import Client
   ...:
   ...: client = Client("NCEDC", debug=True)
   ...:
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f8c46195190>]
Base URL: http://service.ncedc.org
Request Headers: {'User-Agent': 'ObsPy/1.3.0 (macOS-10.16-x86_64-i386-64bit, Python 3.9.12)'}
Downloading http://service.ncedc.org/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://service.ncedc.org/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://service.ncedc.org/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://service.ncedc.org/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://service.ncedc.org/fdsnws/event/1/contributors with requesting gzip compression
Downloaded http://service.ncedc.org/fdsnws/event/1/application.wadl with HTTP code: 200
Downloaded http://service.ncedc.org/fdsnws/event/1/contributors with HTTP code: 200
Downloaded http://service.ncedc.org/fdsnws/station/1/application.wadl with HTTP code: 200
Downloaded http://service.ncedc.org/fdsnws/dataselect/1/application.wadl with HTTP code: 200
Downloaded http://service.ncedc.org/fdsnws/event/1/catalogs with HTTP code: 200
Traceback (most recent call last):

  File ~/miniconda3/envs/gmprocess/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3398 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [1] in <cell line: 3>
    client = Client("NCEDC", debug=True)

  File ~/miniconda3/envs/gmprocess/lib/python3.9/site-packages/obspy/clients/fdsn/client.py:276 in __init__
    self._discover_services()

  File ~/miniconda3/envs/gmprocess/lib/python3.9/site-packages/obspy/clients/fdsn/client.py:1543 in _discover_services
    self.services["event"] = WADLParser(wadl).parameters

  File ~/miniconda3/envs/gmprocess/lib/python3.9/site-packages/obspy/clients/fdsn/wadl_parser.py:28 in __init__
    doc = etree.parse(io.BytesIO(wadl_string)).getroot()

  File src/lxml/etree.pyx:3538 in lxml.etree.parse

  File src/lxml/parser.pxi:1893 in lxml.etree._parseDocument

  File src/lxml/parser.pxi:1913 in lxml.etree._parseMemoryDocument

  File src/lxml/parser.pxi:1800 in lxml.etree._parseDoc

  File src/lxml/parser.pxi:1141 in lxml.etree._BaseParser._parseDoc

  File src/lxml/parser.pxi:615 in lxml.etree._ParserContext._handleParseResultDoc

  File src/lxml/parser.pxi:725 in lxml.etree._handleParseResult

  File src/lxml/parser.pxi:654 in lxml.etree._raiseParseError

  File <string>:1
XMLSyntaxError: Space required after the Public Identifier, line 1, column 50
```

### ObsPy Version?

1.3.0

### Operating System?

OSX

### Python Version?

Python 3.9.12

### Installation Method?

pip

**Comment by ghartman-usgs** [comment] 2022-09-02 22:48
I'm getting the same using Python 3.8 with obspy 1.2.2 on RHEL8.  From what I can tell it appears to be a server side issue.
Running curl on the URLs found in the debug output returns a 301 redirect.
When I follow the URL provided in the redirect response, I see the expected wadl/xml response.
I'm not sure if obspy handles HTTP redirects though.

**Comment by kkappler** [comment] 2022-09-03 18:17
Same here.
obspy.__version__ = 1.3.0
installed by pip

The issue seems to be that they have changed their urls.

At line 1438 in obspy/clients/fdsn/client.py is a function `_discover_services`.

At line 1450 this calls:
`
urls = [self._build_url(service, "application.wadl")
                for service in services]
`

and the value of urls is:

> ['http://service.ncedc.org/fdsnws/dataselect/1/application.wadl',` 'http://service.ncedc.org/fdsnws/event/1/application.wadl', 'http://service.ncedc.org/fdsnws/station/1/application.wadl']

When these get passed to obspy/clients/fdsn/wadl_parser.py, when I interact with the debugger, I see these messages:

> b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>301 Moved Permanently</title>\n</head><body>\n<h1>Moved Permanently</h1>\n<p>The document has moved <a href="https://service.ncedc.org/ws/fdsnws.event.1-application.wadl">here</a>.</p>\n</body></html>\n'

The paste above doesn't quite show what I want because embedded html, but the new address is:
"https://service.ncedc.org/ws/fdsnws.event.1-application.wadl", so maybe this value should go into the "event" entry of urls.

I tried overwritting `urls` with:

`
urls[0] = "https://service.ncedc.org/ws/fdsnws.dataselect.1-application.wadl"

urls[1] = "https://service.ncedc.org/ws/fdsnws.event.1-application.wadl"

urls[2] = "https://service.ncedc.org/ws/fdsnws.station.1-application.wadl"
`

I know this is not the whole issue though, as this does not fix the problem entirely.

However, in my case I am only interested in getting data and station metadata.  When I modify from 

`services = ["dataselect", "event", "station"]`
to
`services = ["dataselect",  "station"]`

and set 
`
urls[0] = "https://service.ncedc.org/ws/fdsnws.dataselect.1-application.wadl"

urls[1] = "https://service.ncedc.org/ws/fdsnws.station.1-application.wadl"
`
I am able to run my tests... 

I can try to take a look at what is going on with event

**Comment by kkappler** [comment] 2022-09-04 19:56
Whoops, I forked master and added a commit on a branch, but then when I was going to create a PR, I see that I should have forked maintenance_1.3.x branch.  Not quite sure how to fix that without deleting my fork from my github and re-forking it, which may have unintended consequences.

I'll await suggestion on how to proceed ... @megies I see you are contributing to `maintenance_1.3.x`.  If you have a suggestion please let me know.

**Comment by saltyfishwoods** [comment] 2022-09-05 02:20
@kkappler Thank you so much for your solution. I am new to python, so I still have one small question here. In your answer, you used the local variable 'subpath', but it was not defined anywhere. Could you explain this a little bit clearer?

**Comment by kkappler** [comment] 2022-09-05 04:49
@saltyfishwoods : Glad this helped.  The keyword argument `subpath`  (set in `build_url` around line 1667) has default value `subpath='fdsnws'`, but it looks like for the renamed NCEDC urls it should be replaced with "ws/fdsnws".

It is passed to the function `build_url` (around line 1433) within `_build_url` defined around line 1422.  It is a renaming of the `Client` class variable `url_subpath`.  

It looks like for the renamed NCEDC urls it should be replaced with "ws/fdsnws". I guessed by reading the redirect messages while debugging, so not sure if this is NCEDC's long term plan.

**Comment by celsoa** [comment] 2022-09-06 06:27
The mass downloader is producing a similar error starting in WADLParser, but not clear if the problem is the NCEDC client, though it sounds like it from the discussion above. A data request from August 31 worked fine, but doesn't work as of Sept. 5, so it sounds like a recent misconfigured/updated URL on the server side.

```
[2022-09-05 16:19:16,543] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for AUSPASS, BGR, EMSC, ETH, GEOFON, GEONET, GFZ, ICGC, IESDMC, INGV, IPGP, ISC, KNMI, KOERI, LMU, NCEDC, NIEP, NOA, RESIF,         RESIFPH5, SCEDC, TEXNET, UIB-NORSAR, USGS, USP, ORFEUS, IRIS.
[2022-09-05 16:19:17,666] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'ISC' as it does not have 'dataselect' and/or 'station' services.
[2022-09-05 16:19:17,698] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'EMSC' as it does not have 'dataselect' and/or 'station' services.
[2022-09-05 16:19:17,780] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'RESIFPH5' as it does not have 'dataselect' and/or 'station' services.
[2022-09-05 16:19:18,293] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'USGS' as it does not have 'dataselect' and/or 'station' services.
Traceback (most recent call last):                                                 
  File "/home/usert540/folder/utilx9/gw.py", line 249, in rasfd                    
    mdl = MassDownloader()                                                         
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 113, in __init__
    self._initialize_clients()                                                     
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 327, in _initialize_clients
    clients = p.map(_get_client, self.providers)                                   
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/multiprocessing/pool.py", line 364, in map 
    return self._map_async(func, iterable, mapstar, chunksize).get()               
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/multiprocessing/pool.py", line 771, in get 
    raise self._value                                                              
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))                                           
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))                                                        
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 302, in _get_client
    this_client = Client(client_name, debug=self.debug)                            
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 276, in __init__
    self._discover_services()                                                      
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1543, in _discover_services
    self.services["event"] = WADLParser(wadl).parameters                           
  File "/home/usert540/miniconda3/envs/env294/lib/python3.9/site-packages/obspy/clients/fdsn/wadl_parser.py", line 28, in __init__
    doc = etree.parse(io.BytesIO(wadl_string)).getroot()                           
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse                        
  File "src/lxml/parser.pxi", line 1893, in lxml.etree._parseDocument              
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument        
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc                
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc       
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult        
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError          
  File "<string>", line 1                                                       
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 50
```

**Comment by megies** [comment] 2022-09-08 10:58
I just tried and did not get any error during NCEDC client initialization. My guess is this was fixed at server side?

I'll close this on that assumption for now. If there are further issues, please do reopen.

Also CCing @NCEDC

**Closed by megies** 2022-09-08 10:58 UTC
Labels: external, .clients.fdsn, bug-unconfirmed

**Comment by stephanezuzlewski** [comment] 2022-09-08 17:18
This issue was brought up to me a couple days ago. The culprit was a setting to enforce https connections. As you noticed, everything should be working now. Apologies for the disruption!
