### ISSUE TITLE
A possible rotate error cause by invalid tr.id

### ISSUE THREAD

**Issue by SuwenJunliu** [obspy/obspy#3373] opened 2023-11-19 13:55 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

There might be a bug when performing the```st.rotate() ``` method.

# Description

## Problem Overview
When using the st.rotate() method in ObsPy, an issue arises when the tr.id of a trace is invalid. This problem occurs when creating a trace using the [Trace class](https://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.id.html#obspy.core.trace.Trace.id) or reading a SAC file from an external source. It appears that ObsPy does not validate the tr.id, leading to unexpected behavior.
```
from obspy.core.trace import Trace

# Create a trace with an invalid tr.id
meta = {'station': 'MANZ.', 'network': 'BW', 'channel': 'EHZ'}
tr = Trace(header=meta)
print(tr.id)  # Outputs 'BW.MANZ...EHZ'

# Performing st.rotate() causes issues when unpacking tr.id
net, sta, loc, cha = tr.id.split(".")
```

## Additional Context 
The problem becomes evident when using the st.rotate() method, which internally involves unpacking the components of tr.id. This can lead to errors and unexpected behavior due to the invalid format of tr.id.

The tricky thing is that, if we just set the tr.id by assignment, obspy will raise the error.

```
>>> tr.id = "invalid.trid"
```

```
Traceback (most recent call last):
  File "/Users/junliu/anaconda3/envs/obspy/lib/python3.11/site-packages/obspy/core/trace.py", line 905, in id
    net, sta, loc, cha = value.split(".")
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/junliu/anaconda3/envs/obspy/lib/python3.11/site-packages/obspy/core/trace.py", line 486, in __setattr__
    return super(Trace, self).__setattr__(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junliu/anaconda3/envs/obspy/lib/python3.11/site-packages/obspy/core/trace.py", line 912, in id
    raise ValueError(msg)
ValueError: Not a valid SEED ID: 'invaild.trid'
```

And these debugging message is much more clear ( ValueError: Not a valid SEED ID: 'invaild.trid' )

## Proposed Solution

Consider adding validation checks for tr.id when creating instances of the Stream or Trace class. This would help ensure that tr.id follows a valid format, preventing unexpected errors during operations like st.rotate().

### Code to Reproduce

```python
from obspy.core import read
st = read()
st.write("RJOB", format = "SAC")


# Then modify the header of sacfiles by sac
# All those command execute by sac
# r RJOB*
# ch KSTNM RJOB..
# wh

# read those sac file and perform the st.rotate()
st = read("RJOB*")
st.rotate(method = "NE->RT")
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/junliu/anaconda3/envs/obspy/lib/python3.11/site-packages/obspy/core/stream.py", line 2756, in rotate
    net, sta, loc, cha = tr.id.split(".")
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
```

### ObsPy Version?

1.4.0

### Operating System?

MacOS(M1)

### Python Version?

3.11

### Installation Method?

conda

**Comment by SuwenJunliu** [comment] 2023-11-20 11:00
> You used a dot '.' in your station code which is not allowed character. You can only use uppercase [A-Z] and numeric [0-9] characters in SEED files (see the [SEED Manual](http://www.fdsn.org/pdf/SEEDManual_V2.4.pdf)) or you can also add a dash '-' according to the (already accepted) [FDSN Source Identifier proposal](http://docs.fdsn.org/projects/source-identifiers/en/v1.0/). The question is whether ObsPy should test the correctness of station identifiers.

You are absolutely right. The core idea is that ObsPy does not check the correctness of station identifiers when reading the data from SAC files, or it should raise a warning at least. Otherwise, there should be a try/except sentence before every ```tr.id.split(".")```  sentence.

**Comment by megies** [comment] 2023-11-21 09:37
I guess we could show a warning if a NSLC code gets set with a dot in it. But if I understand the report correctly, we kind of gracefully error out with a traceback that should make clear what the problem is (too many dots in the trace id).

But yes, ideally we should change this, probably best solution would be to not rely on `tr.id.split()` but rather use the actual attributes `tr.stats.station` etc. Then it should also work doing the operation with dots in some of the station/... codes.

**Comment by SuwenJunliu** [comment] 2023-11-21 12:01
These solution looks fine to me. Another problem (or side effect?) is that there are still some "tr.id.split" in code.

```
$ grep -r "tr.id.split("
obspy/core/stream.py:            net, sta, loc, cha = tr.id.split(".")
obspy/signal/trigger.py:        sta = tr_id.split(".")[1]
obspy/signal/trigger.py:        sta = tr_id.split(".")[1]
obspy/signal/trigger.py:        event['stations'] = [tr_id.split(".")[1]]
obspy/signal/trigger.py:            tmp_sta = tmp_tr_id.split(".")[1]
``` 

So the next question is "Should we use the same solution in obspy/signal/trigger.py"?

It is my honor if I could contribute to ObsPy by making a PR. :D

**Comment by megies** [comment] 2023-11-21 16:25
> Another problem (or side effect?) is that there are still some "tr.id.split" in code.

I went through the code as well and to me it looked like the other occurences were this `.split()` is used can not be avoided, really. These are tied to SEED conventions more tightly, and SEED does not allow a dot in these fields.

In the trigger routine you mention it could be avoided, but it would mean a change in some of the return types (return values have more items if we split up the SEED string), so I am not sure if it is worth doing / whether we should do it.

This fix in rotate was trivial so there was no harm involved.

**Comment by megies** [comment] 2023-11-21 16:26
In general, it is just good practice to avoid "dots" in these fields.

**Comment by megies** [comment] 2024-02-22 10:44
fixed by linked PRs

**Closed by megies** 2024-02-22 10:44 UTC
Labels: bug
