### ISSUE TITLE
FDSNNoDataException

### ISSUE THREAD

**Issue by maaz-shahid99** [obspy/obspy#3149] opened 2022-09-21 19:23 UTC
Not able to get response data. 

 client.get_stations(network="XA", station="S11", channel="SPZ")

     msg = ("Bad request. If you think your request was valid "
             "please contact the developers.")

FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:

**Comment by calum-chamberlain** [comment] 2022-09-21 20:01
Kia ora @maaz-shahid99 - I have deleted your comment on #2429 as it appears to be a duplicate of this issue. That comment was:

> FDSNNoDataException("No data available for request.",)
> `inv = client.get_stations(network="XA", station="S11", channel="SPZ", level="response", starttime=t1)`
> 
> I'm requesting data for Apollo alsep missions from IRIS. Is the data not available? Although I can download the data from the iris website directly

As far as I can tell there is nothing wrong with ObsPy. IRIS reports valid channels as SHZ, MHZ, MH1 and MH2 - you can check what channels they have [here](http://ds.iris.edu/mda/XA/S11/?starttime=1969-07-21&endtime=1969-08-26). Perhaps you had a typo when requesting channel SPZ rather than SHZ?

**Comment by megies** [comment] 2022-09-29 12:27
Closing for now. Please reopen if needed

**Closed by megies** 2022-09-29 12:27 UTC
