### ISSUE TITLE
Error reading REFTEK130 file with unoccupied first three channels

### ISSUE THREAD

**Issue by jjfarrugia** [obspy/obspy#2101] opened 2018-04-09 17:50 UTC
ObsPy version 1.1.0 (Windows) installed via Anaconda

Hello ObsPy community, 

I'm facing the situation where three component data has been recorded on the velocity channels (4-6) of a reftek 130, but the acceleration channels (1-3) of the datalogger are unoccupied (file 093000000_001B7740 attached). Is there a way to only read in the data on the velocity channels 4-6? 
 
Using the read function on the attached file gives the following error message:
`IndexError: index 0 is out of bounds for axis 0 with size 0`

Attached file:
[093000000_001B7740.zip](https://github.com/obspy/obspy/files/1891075/093000000_001B7740.zip)

Datalogger setup:
AAAA Ch 1-3    Not connected
AAAA Ch 4-6    3C surface geophone

**Comment by megies** [comment] 2018-04-10 08:10
Please post full code to reproduce and full error traceback.

**Comment by jjfarrugia** [comment] 2018-04-10 14:48
@megies Thanks Tobias, 

Code is simply:

`st = read("093000000_001B7740")`

**Comment by megies** [comment] 2018-04-11 09:03
Debugging into the failing read operation, I see a pair of EH and ET packet for channel number 0 (actually the first and last packet in the file -- no idea if Reftek does that by default, wrapping the file in a EH/ET pair for channel 0 if there is no data in channel 0), stating a time of first and last sample of the event, but there are no data (DT) packets for those header packets. That looks like a problem with the file. But in any case we can still work around channels that have some metadata packets but no data packets.

```
(Pdb++) print(EHPacket(packets[0]))
EH Packet
	packet_sequence: 0
	experiment_number: 0
	unit_id: ABA1
	byte_count: 416
	time: 2017-09-08T09:30:00.000000Z
	event_number: 937
	data_stream_number: 0
	data_format: C0
	flags: 0
	--------------------
	_reserved_2:         
	_reserved_3:                                                                                                                                                             
	channel_ad_resolution_code: (None, None, None, u'3', u'3', u'3', None, None, None, None, None, None, None, None, None, None)
	channel_adjusted_nominal_bit_weights: (None, None, None, u'104.2 mV', u'104.2 mV', u'104.2 mV', None, None, None, None, None, None, None, None, None, None)
	channel_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_fsa_code: (None, None, None, u'3', u'3', u'3', None, None, None, None, None, None, None, None, None, None)
	channel_gain_code: (None, None, None, u'1', u'1', u'1', None, None, None, None, None, None, None, None, None, None)
	channel_sensor_fsa_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_sensor_units_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_sensor_vpu: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_true_bit_weights: (None, None, None, u'1.587 uV', u'1.586 uV', u'1.586 uV', None, None, None, None, None, None, None, None, None, None)
	detrigger_time: None
	digital_filter_list:                 
	first_sample_time: 2017-09-08T09:30:00.000000Z
	last_sample_time: None
	position: N 4838.924W12326.769+00016
	reftek_120:                                                                                 
	sampling_rate: 500
	station_channel_number: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	station_comment:                                         
	station_name: Surf
	station_name_extension: a
	stream_name: NEW_STREAM      
	time_quality: 0
	time_source: 2
	total_installed_channels: 6
	trigger_time: 2017-09-08T09:30:00.000000Z
	trigger_time_message: Trigger Time = 2017251093000000

	trigger_type: CON 
(Pdb++) print(EHPacket(packets[1]))
ET Packet
	packet_sequence: 3158
	experiment_number: 0
	unit_id: ABA1
	byte_count: 416
	time: 2017-09-08T09:30:00.000000Z
	event_number: 937
	data_stream_number: 0
	data_format: C0
	flags: 0
	--------------------
	_reserved_2:         
	_reserved_3:                                                                                                                                                             
	channel_ad_resolution_code: (None, None, None, u'3', u'3', u'3', None, None, None, None, None, None, None, None, None, None)
	channel_adjusted_nominal_bit_weights: (None, None, None, u'104.2 mV', u'104.2 mV', u'104.2 mV', None, None, None, None, None, None, None, None, None, None)
	channel_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_fsa_code: (None, None, None, u'3', u'3', u'3', None, None, None, None, None, None, None, None, None, None)
	channel_gain_code: (None, None, None, u'1', u'1', u'1', None, None, None, None, None, None, None, None, None, None)
	channel_sensor_fsa_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_sensor_units_code: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_sensor_vpu: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	channel_true_bit_weights: (None, None, None, u'1.587 uV', u'1.586 uV', u'1.586 uV', None, None, None, None, None, None, None, None, None, None)
	detrigger_time: 2017-09-08T09:59:59.998000Z
	digital_filter_list:                 
	first_sample_time: 2017-09-08T09:30:00.000000Z
	last_sample_time: 2017-09-08T09:59:59.998000Z
	position: N 4838.924W12326.770+00015
	reftek_120:                                                                                 
	sampling_rate: 500
	station_channel_number: (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
	station_comment:                                         
	station_name: Surf
	station_name_extension: a
	stream_name: NEW_STREAM      
	time_quality: 0
	time_source: 2
	total_installed_channels: 6
	trigger_time: 2017-09-08T09:30:00.000000Z
	trigger_time_message: Trigger Time = 2017251093000000

	trigger_type: CON 
```

**Comment by megies** [comment] 2018-04-11 09:08
Furthermore the file only has event header (EH) and event trailer (ET) packet for channel 0, while all the data is for channels 3-5.

**Comment by megies** [comment] 2018-04-11 09:15
Ah, nonsense.. there's always just one EH packet and it always has channel 0, so the file is valid and it's a bug on our end. The problem only shows up with files that do not have data in the first channel (channel number 0).

**Comment by megies** [comment] 2018-04-11 09:26
@jjfarrugia can I use a few samples of that file for a test case (i.e. include a few samples in our test suit)?

**Comment by megies** [comment] 2018-04-11 11:55
Fixed in maintenance branch and will be part of next bug fix and major release.

**Closed by megies** 2018-04-11 11:55 UTC
Labels: .io, bug

**Comment by megies** [comment] 2018-04-11 15:27
Might be some time until next release.. so for the short term you might just want to monkey patch your obspy installation with 3fa7eb9c8bafc5a7fca83269885cdd3d527084b4 if you're feeling brave ;-)
