### ISSUE TITLE
Spelling mistake in default window in obspy.core.trace.Trace.resample

### ISSUE THREAD

**Issue by seismo-savi** [obspy/obspy#3135] opened 2022-09-03 05:28 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Looks like the default window method for obspy.core.stream.Stream.resample has a spelling mistake - the scipy function called inside resample (scipy.signal.get_window) requires specifying a window as str or float. Obspy defaults to "hanning", but the scipy.signal.get_window docs (https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html#scipy.signal.get_window) suggest there's no such thing as a 'hanning' window - there's the 'hann' and 'hamming' options. Not sure what the intention for the default obspy resample method was. Code below is obviously station specific but it was tested against a local stream archive as well with the same error.

### Code to Reproduce

```python
from obspy.clients.fdsn import Client
from obspy import UTCDateTime

client = Client('IRIS')
print(client)

net  =  'II'
sta  =  'ESK'
loc  =  '00'
com  =  'BHZ'

st = client.get_waveforms(net,  sta, loc, com,
                          starttime,  endtime)

final_st = st.copy().resample(sampling_rate=15)
```

### Error Traceback

```Python traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/scipy/signal/windows/_windows.py:2214, in get_window(window, Nx, fftbins)
   2213 try:
-> 2214     beta = float(window)
   2215 except (TypeError, ValueError) as e:

ValueError: could not convert string to float: 'hanning'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/scipy/signal/windows/_windows.py:2232, in get_window(window, Nx, fftbins)
   2231 try:
-> 2232     winfunc = _win_equiv[winstr]
   2233 except KeyError as e:

KeyError: 'hanning'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 final_st = st.copy().resample(sampling_rate=15)

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/obspy/core/stream.py:2351, in Stream.resample(self, sampling_rate, window, no_filter, strict_length)
   2296 """
   2297 Resample data in all traces of stream using Fourier method.
   2298 
   (...)
   2348 BW.RJOB..EHE | 2009-08-24T00:20:03.000000Z ... | 10.0 Hz, 300 samples
   2349 """
   2350 for tr in self:
-> 2351     tr.resample(sampling_rate, window=window,
   2352                 no_filter=no_filter, strict_length=strict_length)
   2353 return self

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/obspy/core/util/decorator.py:237, in skip_if_no_data(func, *args, **kwargs)
    235 if not args[0]:
    236     return
--> 237 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/obspy/core/trace.py:282, in _add_processing_info(func, *args, **kwargs)
    280 info = info % "::".join(arguments)
    281 self = args[0]
--> 282 result = func(*args, **kwargs)
    283 # Attach after executing the function to avoid having it attached
    284 # while the operation failed.
    285 self._internal_add_processing_info(info)

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/obspy/core/trace.py:1744, in Trace.resample(self, sampling_rate, window, no_filter, strict_length)
   1742     large_w = window
   1743 else:
-> 1744     large_w = np.fft.ifftshift(get_window(window,
   1745                                           self.stats.npts))
   1746 x_r *= large_w[:self.stats.npts // 2 + 1]
   1747 x_i *= large_w[:self.stats.npts // 2 + 1]

File ~/opt/anaconda3/envs/seismo/lib/python3.9/site-packages/scipy/signal/windows/_windows.py:2234, in get_window(window, Nx, fftbins)
   2232     winfunc = _win_equiv[winstr]
   2233 except KeyError as e:
-> 2234     raise ValueError("Unknown window type.") from e
   2236 if winfunc is dpss:
   2237     params = (Nx,) + args + (None,)

ValueError: Unknown window type.
```

### ObsPy Version?

1.3.0

### Operating System?

Mac OSMonterrey

### Python Version?

3.9.13

### Installation Method?

conda

**Comment by calum-chamberlain** [comment] 2022-09-03 08:48
Duplicate of #3116, fixed by #3117.  Check those issues for workarounds and forthcoming release fixes.

Please do check for existing issues before posting: github's issues search is quite helpful for this. In this case, searing for `hanning` shows the duplicate issues quite quickly.

**Closed by calum-chamberlain** 2022-09-03 08:48 UTC
Labels: bug-unconfirmed
