### ISSUE TITLE
UTCDateTime before 1900

### ISSUE THREAD

**Issue by MMesch** [obspy/obspy#1318] opened 2016-03-07 14:49 UTC
**Description:**
printing UTCDateTime raises Exceptions before 1900 whereas datetime and UTCDateTime cover in principle the year 1 all the way to the year 9999.

**Remarks:**
- `obspy.__version__: 1.0.0.dev0+20.g4c9f93ae96.obspy.maintenance.1.0.x`
- `Python 2.7.11 |Continuum Analytics, Inc.`
- this 'bug' already appeared in #168

**Example:**

```
from obspy import UTCDateTime
t1 = UTCDateTime(1, 1, 1)
print t1.datetime
print t1
```

**Comment by barsch** [comment] 2016-03-07 15:03
as you didn't post a concrete example with full traceback, I assume it the same issue as before:

```
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]

In [1]: import datetime
In [2]: datetime.datetime(1,1,1)
Out[2]: datetime.datetime(1, 1, 1, 0, 0)
In [4]: print datetime.datetime(1,1,1)
0001-01-01 00:00:00
In [5]: print datetime.datetime(1,1,1).strftime("%j")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-14eeeba5d56d> in <module>()
----> 1 print datetime.datetime(1,1,1).strftime("%j")

ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by barsch** [comment] 2016-03-07 15:06
oh and it works for Python 3.4
```
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AMD64)]

In [1]: import datetime
In [2]: print(datetime.datetime(1,1,1).strftime("%j"))
001
```

**Comment by MMesch** [comment] 2016-03-07 15:28
yes. I suggest catching the Exception because it is not necessary ...

**Comment by barsch** [comment] 2016-03-07 15:37
its an exception coming from the Python's ```datetime.strftime``` function only raised for Python 2.7 (don't know about Python 3.0-3.3) - so what do you suggest to catch there as its an issue with Python and not ObsPy.

Catching the exception and silently ignoring it is IMHO no optionen - especially if this is fixed in newer Python versions. You can always monkey patch the ```print()``` function of the ```UTCDateTime``` class.

**Comment by MMesch** [comment] 2016-03-07 15:55
well I would just catch and say: can't print date before 1900 or something. This improves usability without hurting anyone and makes the code more stable. Only disadvantage is that you need two extra lines of code. Just my opinion though. I agree that it is not the most important issue ...

**Comment by barsch** [comment] 2016-03-07 16:11
ok I had a look into the code - now I remember that we fixed that: https://github.com/obspy/obspy/blob/master/obspy/core/utcdatetime.py#L800 - and this actually works for python 2.7.x:
```
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]

In [1]: import datetime
In [2]: datetime.datetime(1,1,1).utctimetuple().tm_yday
Out[2]: 1
```

So I wonder why this issue started reappearing.. Can you please post a concrete example where your issue pops up - thanks!

**Comment by MMesch** [comment] 2016-03-08 11:05
Well the issue pops up in my and your example above. But I can post it again:
```
from obspy import UTCDateTime
In [1]: from obspy import UTCDateTime
In [2]: t1 = UTCDateTime(1, 1, 1)
In [3]: print t1
Out[3]: ---------------------------------------------------------------------------
[...]
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```

to me this is an unneccesary and undocumented limitation of UTCDateTime even if the underlying cause comes from python itself. Print is a function that pops up very often. I think I don't need to give a specific use case. Also this behavior is very easy to fix. Yes, the user could catch the Exception as well, but it is a hassle to do this just because of a print function. 

To me one (not very convincing) argument not to do sth. is that maybe in a few years nobody cares about python 2.7 and it works later anyway. Keep in mind that UTCDateTime is not a copy of datetime but something on top. It doesn't have to inherit all of datetimes problems which belongs to the standard library and can't be updated easily.

So my opinion is that it is better to catch the Exception with a meaningful message or an adjusted print function. Anyway, I think I made my point clear enough. No need to repeat everything and as I said it is not the most important issue, so I'll leave it as it is :)

**Comment by barsch** [comment] 2016-03-08 11:27
Matthias, I wasn't aware that the example above gave that exception - you did not give a full traceback but stated that "this bug already appeared in #168" - and I was talking about the issue in #168, showing examples and the fix for it at that time. A meaningful example with a full traceback would have spared me the time to look into that.

Anyway, you are right and I can reproduce this issue and a workaround should be possible.

**Comment by MMesch** [comment] 2016-03-08 13:09
OK, sorry about that. I'll provide input AND output for the minimum working example next time !

**Comment by MMesch** [comment] 2016-03-08 13:11
And I will update the issue template to remind me doing so! :)

**Comment by barsch** [comment] 2016-03-08 13:18
no problem, sorry for all the fuzz above and while trying to fix this issue I discovered another problem with the current UTCDateTime implementation:
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]

In [1]: from obspy import UTCDateTime
In [2]: UTCDateTime(1,1,1,1,1,1,1)
Out[2]: 0001-01-01T01:01:01.000000Z   # microseconds incorrect!
In [3]: UTCDateTime(1,1,1,1,1,1,1).datetime
Out[3]: datetime.datetime(1, 1, 1, 1, 1, 1)   # microseconds missing!
In [4]: from datetime import datetime
In [5]: datetime(1,1,1,1,1,1,1)
Out[5]: datetime.datetime(1, 1, 1, 1, 1, 1, 1)   # microseconds correct
``` 
I'm currently playing with it - my guess we are going to switch back to datetime.datetime instead of float within UTCDateTime especially since we don't have to support Python2.6 anymore ...

**Comment by megies** [comment] 2016-11-17 13:22
This hasn't seen any activity, so I'll bump this to 1.2.0.

**Comment by nackerley** [comment] 2016-12-21 21:42
I ran into this bug when attempting a Catalog.plot(). I haven't figured out how to install basemap or cartopy under python 3.4, so I tried it in python 2.7, where I run into this error. It seems like, at this point, catalogs with events prior to 1900 can't be plotted on maps.

**Closed** 2017-01-21 18:08 UTC
Labels: .core, priority: high
