### ISSUE TITLE
miniSEED to SEG-Y

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#2073] opened 2018-02-13 16:05 UTC
Hi all,

I'm trying to write seg-y files from miniSEED (STEIM-2 compressed) data.

The stream is at 20 sps, I have trimmed the data to a 60 second long segment (1201 samples) and converted the data type to float32, as follows:

```
st = read("WI.DSD.00.BHZ.D.2017.032")
st.trim(st[0].stats.starttime+60, st[0].stats.starttime+120)
st[0].data = np.require(st[0].data, dtype=np.float32)
st.write('/Users/sph1r17/test.segy', format="SEGY", encoding=1)

```
Yet, I still get the following error:

> Traceback (most recent call last):
> File "", line 1, in 
> File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/core/stream.py", line 1443, in write
> write_format(self, filename, **kwargs)
> File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/core.py", line 394, in _write_segy
> segy_file.write(filename, data_encoding=data_encoding, endian=byteorder)
> File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 256, in write
> self._write(file, data_encoding=data_encoding, endian=endian)
> File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 296, in _write
> self.binary_file_header.write(file, endian=endian)
> File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py", line 502, in write
> file.write(pack(format, getattr(self, name)))
> struct.error: 'h' format requires -32768 <= number <= 32767

Here are the header details after trimming and converting the dtype:

> network: WI
> station: DSD
> location: 00
> channel: BHZ
> starttime: 2017-02-01T00:01:00.025000Z
> endtime: 2017-02-01T00:02:00.025000Z
> sampling_rate: 20.0
> delta: 0.05
> npts: 1201
> calib: 1.0
> _format: MSEED
> mseed: AttribDict({'encoding': 'STEIM2', 'record_length': 512, 'byteorder': '>', 'number_of_records': 4145, 'dataquality': 'M', 'filesize': 2122240})
> processing: ['ObsPy 1.1.0: trim(endtime=UTCDateTime(2017, 2, 1, 0, 2, 0, 25000)::fill_value=None::nearest_sample=True::pad=False::starttime=UTCDateTime(2017, 2, 1, 0, 1, 0, 25000))']

I understand from #1393 that this issue is to do with the number of samples, but the number of samples in my trace is far below the maximum of 32767.

The raw miniSEED file can be found on my Dropbox here: https://www.dropbox.com/s/b8dh36c0h5ig0yk/WI.DSD.00.BHZ.D.2017.032?dl=0

I'm running ObsPy 1.1.0 and Python 3.5.

**Comment by megies** [comment] 2018-02-13 16:16
I think this is a duplicate of #1393.

**Comment by ThomasLecocq** [comment] 2018-02-13 16:20
what gives

``st[0].data.ptp()`` 
?

**Comment by shicks-seismo** [comment] 2018-02-13 16:32
Thanks @megies, and I alredy had a good look at #1393. The error is the same, but the context is a bit different - I have already trimmed the stream sufficiently.

@ThomasLecocq :
st[0].data.ptp() = 1302 (before converting to float32) and 1302.0 after converting to float32.

**Comment by ThomasLecocq** [comment] 2018-02-13 16:34
@shicks-seismo just checked it too. The thing is, there is something in the automatic ``segy.trace_headers`` or elsewhere that gets converted to a crazy number that doesn't match ``struct`` type ``h``. 
If you can hack your obspy install, just add some 

``
print(format, name)
``
before
`` 
file.write(pack(format, getattr(self, name)))
``

**Comment by shicks-seismo** [comment] 2018-02-13 16:59
So if I insert 
`print(format, name)` before `file.write(pack(format, getattr(self, name))`, the code keeps failing at Line 502, which occurs even if I insert `print('hello')`. Strange behaviour ...

**Comment by megies** [comment] 2018-02-14 10:41
> Thanks @megies, and I alredy had a good look at #1393

Yeah, sorry, I didn't read until the end of your post right at the start.. 😊

**Comment by shicks-seismo** [comment] 2018-02-16 10:38
Thanks, @megies.

I ran pdf with post-mortem debugger to show what the 'format' and 'name' variables have been set to:

> struct.error: 'h' format requires -32768 <= number <= 32767
> Uncaught exception. Entering post mortem debugging
> Running 'cont' or 'step' will restart the program
> > /Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/segy/segy.py(503)write()
> -> file.write(pack(format, getattr(self, name)))
> (Pdb) print(format)
> b'>h'
> (Pdb) print(name)
> sample_interval_in_microseconds
> (Pdb) struct.error: 'h' format requires -32768 <= number <= 32767

Is this normal behaviour for writing to SEG-Y?

**Comment by megies** [comment] 2018-02-16 10:44
Well.. so if you have 20 Hz data that means your sampling interval is 0.05 seconds or 50,000.0 microseconds (which is > 32767 -- the max for 16bit signed int). So to me it seems that it's what is described in #1393 in https://github.com/obspy/obspy/issues/1393#issuecomment-217026124.

**Comment by shicks-seismo** [comment] 2018-02-16 10:51
Okay - thanks - resampling to 40 sps seems to work. You were right that it was a duplicate :)

**Closed** 2018-02-16 10:51 UTC
Labels: .io.segy, duplicate

**Comment by megies** [comment] 2018-02-16 10:55
@shicks-seismo how's your git(hub)-fu feeling today? 😉  #1393 is still waiting for somebody to work on it (i.e. adding some meaningful exception messages for problems like yours)..

**Comment by shicks-seismo** [comment] 2018-02-16 11:19
Well I am currently at home recovering from knee surgery, so could be a nice thing to do. However, I don't think I'm familiar enough with SEG-Y to get this done robustly and to speak in the right language - the file conversion above was a fairly ad-hoc request from an active-source friend.
