### ISSUE TITLE
The smallest possible mini-SEED record is made up of 128 bytes

### ISSUE THREAD

**Issue by boulanouar1** [obspy/obspy#2877] opened 2021-09-11 13:07 UTC
Dear all, I have a code on python. When I run it, it gives me this error, 

 raise ObsPyMSEEDFilesizeTooSmallError(msg)
obspy.io.mseed.ObsPyMSEEDFilesizeTooSmallError: The smallest possible mini-SEED record is made up of 128 bytes. The passed buffer or file contains only 0.
To your knowledge the code works with a test data of mseed. By it does not work with my one data. 
Does anyone an idea?
Thank you all,
Best Regards 

Setup details:
Python 3.8.8
Obspy 1.2.2 using anaconda
Windows 10

**Comment by jkmacc-LANL** [comment] 2021-09-11 13:28
It just sounds like the file is not valid.  Are you able to read it in a different non-ObsPy program?

**Comment by boulanouar1** [comment] 2021-09-11 13:31
@jkmacc-LANL thanks for your quick answer, 
Of course, I can read it using jupter of anaconda or others like Seisan
Best regards

**Comment by calum-chamberlain** [comment] 2021-09-12 21:15
Can you share the file you are trying go read? 

I assume that this error is coming from a simple `st = read(file)` call, but if your code is doing something else please share the code.

To clarify, what do you mean by being able to read it using "jupter of anaconda"?

**Comment by boulanouar1** [comment] 2021-09-13 11:06
@calum-chamberlain Thank you so much for your reply,
I mean by the data "jupter of anaconda": I read my seismograms using anaconda
Here is the code I am trying to run: [](https://github.com/cormorant/CodaNorm) . the code run perfectly with his test input files.
The input files are : data/TAF/**TAF_data.mseed** , **coda.conf** and catalogs/TAF/**TAF.dat** with TAF is the name of the station
So, could you please use my own data in this link to check where is the problem:
[](https://drive.google.com/drive/folders/1vjN9u8WjDnkumspuvKbY9xPiE-LnaXxf?usp=sharing)
Have a great day
Best Regards

**Comment by calum-chamberlain** [comment] 2021-09-13 23:57
I don't know the code, but when I download the data/TAF/TAF_data.mseed file it appears to be a zip archive containing three miniseed files.  Trying to read this archive itself works, as does reading the individual files extracted from the archive.

If you can identify the line of code that causes the error, and the files that is being read then you might be able to find out what the issue is.

I remain unsure of what you mean by reading your data via anaconda - what do you actually do to read the data? Excuse my ignorance here, but as far as I know anaconda is a Python package manager and distribution, and doesn't inherently provide a way that I know of to read miniseed data, but I'm happy to be corrected!

**Comment by boulanouar1** [comment] 2021-09-14 13:33
@calum-chamberlain thank you for this information,  I think I solved the problem, I mean the code start learning the file of zip archive. 
Now, the program gives me:
Traceback (most recent call last):
  File "CodaNorm3.py", line 854, in <module>
    koef_pears, p = pearsonr(x1, y1)
  File "/home/dell/anaconda3/lib/python3.8/site-packages/scipy/stats/stats.py", line 4016, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.

Here is the code :

# calc coeff correlation (after removing zeros 0)
        koef_pears, p = pearsonr(x1, y1)
        
        # calc regression (polyfit)
        try:
            m, b = np.polyfit(x1, y1, 1)
        except TypeError:
            print("linear fitting error: %s (frequency=%.2f Hz). Skipping..." % (e, Freq))
            continue
        
        Y = m * np.array(x1) + b


Other things, sorry: About the data, I read it by obspy in Jupter 
Thanks for all

**Comment by calum-chamberlain** [comment] 2021-09-14 21:20
This is not an obspy issue, and you should redirect your issue to the github repo of the code you are using.  I'm going to close this now that you have sorted the obspy related issues.

**Closed by calum-chamberlain** 2021-09-14 21:20 UTC
