### ISSUE TITLE
add a unique method to inventory?

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1176] opened 2015-11-12 16:13 UTC
Could you add a `unique` function to remove duplicated stations in the `inventory`?

currently the `__add__` method simply combine two inventory without check, so does the `select` function.

```
inv = obspy.read_inventory()
inv.select(station='WET')
[out]: Inventory created at 2014-03-03T11:07:06.198000Z
    Created by: fdsn-stationxml-converter/1.0.0
            http://www.iris.edu/fdsnstationconverter
    Sending institution: Erdbebendienst Bayern
    Contains:
        Networks (1):
            GR
        Stations (1):
            GR.WET (Wettzell, Bavaria, GR-Net)
        Channels (9):
            GR.WET..BHE, GR.WET..BHN, GR.WET..BHZ, GR.WET..HHE, GR.WET..HHN,
            GR.WET..HHZ, GR.WET..LHE, GR.WET..LHN, GR.WET..LHZ
inv += inv
inv.select(station='WET')
[out]: Inventory created at 2015-11-12T16:06:45.682838Z
    Created by: ObsPy 0.0.0+archive
            http://www.obspy.org
    Sending institution: Erdbebendienst Bayern
    Contains:
        Networks (2):
            GR
            GR
        Stations (2):
            GR.WET (Wettzell, Bavaria, GR-Net)
            GR.WET (Wettzell, Bavaria, GR-Net)
        Channels (18):
            GR.WET..BHE, GR.WET..BHE, GR.WET..BHN, GR.WET..BHN, GR.WET..BHZ,
            GR.WET..BHZ, GR.WET..HHE, GR.WET..HHE, GR.WET..HHN, GR.WET..HHN,
            GR.WET..HHZ, GR.WET..HHZ, GR.WET..LHE, GR.WET..LHE, GR.WET..LHN,
            GR.WET..LHN, GR.WET..LHZ, GR.WET..LHZ
```

**Comment by krischer** [comment] 2015-11-12 18:13
We would already have done this (it would be very natural to do it during the `__add__` method) but it is unfortunately a more complex operation than expected and sometimes there is no obviously correct way to do it.

The issue is mainly with the meta information of the station (and network). Many of these can only be filled from the network provider who has that information. Lots of things might differ for the two station objects to be merged: start and end dates, restricted status, availability, total and selected number of stations, maybe even the coordinates, ...

At that points its not clear what to do - at least to me.

I would nonetheless also really like to have this functionality so if we can come up with a solid way of doing it I'd be more than happy to add it (PRs are of course also welcome ;-)

I did something very similiar here if somebody want to look at an example implementation: https://github.com/SeismicData/pyasdf/blob/master/pyasdf/inventory_utils.py

**Comment by GracielaRojo** [comment] 2021-02-19 12:19
Hello, 
Five years later, I also wonder if this is possible. I agree with @krischer that the meta information does not always match between two clients. 
A turnaround would be to use the mass downloader but only to obtain stations. Is this possible?

**Comment by megies** [comment] 2022-10-14 13:49
> At that points its not clear what to do - at least to me.

Also not clear to me how you would handle something like this, so closing for now

**Closed by megies** 2022-10-14 13:49 UTC
