### ISSUE TITLE
libmseed version 3

### ISSUE THREAD

**Issue by Gilaverbuch** [obspy/obspy#3377] opened 2023-11-28 13:17 UTC
### Problem

Hi, 

There is a new miniSEED version released, libmseed v3 (https://earthscope.github.io/libmseed/). Currently, Obspy does not seem to be able to handle the new miniSEED version. Does anyone know if that will change anytime soon?

Thanks,
Gil

**Comment by QuLogic** [comment] 2023-11-28 23:25
Duplicate of #2376. You should search first, as all the information is in that issue.

**Closed by QuLogic** 2023-11-28 23:25 UTC
Labels: enhancement
