### ISSUE TITLE
numpy fftpack deprecation

### ISSUE THREAD

**Issue by frodo4fingers** [obspy/obspy#2448] opened 2019-09-11 08:45 UTC
# fftpack --> pocketfft

## source
https://docs.scipy.org/doc/numpy/release.html

## my settings
+ manjaro linux
+ obspy installed via AUR
+ python  3.7.4, numpy 1.17.0, obspy is either 1.1.1-1 (AUR, or 0.0.0+archive from `obspy.__version__`)

## found over
+ obspy's method `remove_response` in stream.py
+ traced back to obspy/core/util/misc.py, line 614

i changed `fftpack` to `pocketfft` in lines 614 and 616 and got it back working

## MWE
sorry... can't un-spaghetti my old code, but maybe just try: `from numpy.fft import fftpack`

**Comment by megies** [comment] 2019-09-11 10:30
Duplicate of #2434

**Closed by megies** 2019-09-11 10:30 UTC

**Comment by frodo4fingers** [comment] 2019-09-11 10:50
didn't find that. thx!
