### ISSUE TITLE
decrypting the data downloaded using arclink client

### ISSUE THREAD

**Issue by luigiacris** [obspy/obspy#1314] opened 2016-03-03 17:26 UTC
Hi,
I'm using Obspy 1.0.0
pyOpenSSl version 0.14
M2Crypto 0.23.0
Python version 2.7.9
My issue is due to not successful decrypting of some data.
I use client arclink in a debug mode, so I see that the data are downloaded,
    but then the decrypting procedure fails and
 I get the error message "bad decrypt".
    The decrypting is successful, with same password,
    when I download the data through the web site webdc.eu and I decrypt the
    data  using openssl externally from python.
    with same password and a previous version of Python and Obspy the
    decrypting used to work.
    As the password contains symbols like & and # I set the default encoding
    in our Python setting,  latin-1 as our default
    was ascii and even with encoding utf8 the password could not be read
    properly.
    The password is given in the file dcidpasswords.txt and seems to be read
    properly. and giving the password in the client call as dcid_keys={'GFZ': '????'}
doesn't solve it.
    Do you have any suggestion to understand what went wrong?
    thanks

    Luigia

**Comment by megies** [comment] 2016-03-03 18:18
The interesting part is that the same password worked with obspy `0.10`. I think this must have to do with our Py2/3 compatibility package `future`. Unfortunately our tests for the decryption can't be run, since the arclink node we used for testing decryption seems to be shut down (`webdc.eu`, port 36000), so we would need some replacement test server, I guess..

**Comment by barsch** [comment] 2016-03-03 23:03
can u change the password on the server side? if so, try setting it to plain letters (a-z) only password and test again - if this fails too its probably not related to an encoding issue

otherwise we will need a server + user/pass combo to actually test this ...

**Comment by megies** [comment] 2016-03-04 09:26
@petrrr, any chance you can set up a test account for us at INGV arclink node?

**Comment by luigiacris** [comment] 2016-03-09 13:31
Hi,
I could not get a new password without symbols,
but I learned that the port 36000 is again active, so your decrypting test may work now

**Comment by megies** [comment] 2016-03-10 11:13
> but I learned that the port 36000 is again active, so your decrypting test may work now

I'm getting timeouts when running the tests with passwords on web.dc:3600..

**Comment by luigiacris** [comment] 2016-03-10 12:05
I just tried the port 36000 and I got the data.
It was also working yesterday. 
client1 = Client(host="webdc.eu", port=36000, user="test@obspy.org",dcid_keys={'BIA': 'OfH9ekhi'})
start = UTCDateTime(2010, 1, 1, 10, 0, 0)
end=start+100
stream1 = client1.getWaveform('GE', 'APE', '', 'BHZ', start, end)
![ge_ape_port_3600](https://cloud.githubusercontent.com/assets/17593804/13668944/619a2794-e6c0-11e5-89cf-458789f0f680.png)

**Comment by megies** [comment] 2016-03-10 12:28
Oh.. I got bitten by our institute blocking outgoing high port numbers. Sorry for the confusion. I can confirm that I can get data from port 36000.

However.. the server sends me these (free) data unencrypted, so I get the data even if I put a different (i.e. wrong) password, i.e. we can't confirm the password in our test case works for decrypting, so our decryption test setup is rendered useless.

I think this used to be different back when we implemented those tests (otherwise they would have been pretty useless even at time of implementation -- and I don't think we were so silly at that time :-)).

@luigiacris, are you in contact with the operators of the service? Can you organize a test account for us? That would be great. We would need some mock restricted data to access via some user/password combination, ideally one with special symbols as allowed by the protocol (optionally another combination with plain ascii password as a second test scenario).

**Comment by barsch** [comment] 2016-03-23 14:14
could you please try if https://github.com/obspy/obspy/commit/1e9581fe826c18fa61a8c475f4009faf252e24d3 fixes this issue for you?

**Comment by barsch** [comment] 2016-03-25 11:33
fixed in last release

**Closed by barsch** 2016-03-25 11:33 UTC
Labels: .clients.arclink, bug, PY2/3, regression

**Comment by petrrr** [comment] 2016-04-18 18:18
@megies: Sorry that I have missed this when I was mentioned.
We are currently not using encryption on our side, so it is not just about an account to be created. I think, it is also not possible to configure encryption along with non-encrypted restricted data. At least this was an issue when AlpArray was to be setup. This might be also the reason why encryption was disabled on the test site you were using before, but this is just a guess.
