### ISSUE TITLE
inventory select (via time=) returns nothing with duplicate networks 

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#2857] opened 2021-07-14 10:08 UTC
Noticing something interesting working with a particular inventory ([double_inv.xml.txt](https://github.com/obspy/obspy/files/6815243/double_inv.xml.txt)) where there is substantial overlap of nearly identical data hastily combined from two different agencies.

e.g.

```
Inventory created at 2021-06-23T10:29:52.478881Z
	Created by: ObsPy 1.2.2.post0+324.gb015423c94.filefolder.master
		    https://www.obspy.org
	Contains:
		Networks (2):
			YS (2x)
		Stations (2):
			YS.NAPU (Napu Village, N Sumba Island, Indonesia)
			YS.NAPU (Napu village, north Sumba Island Indonesia)
		Channels (2):
			YS.NAPU..BHZ (2x)
```
The first network spans from 2016-11-22 to 2019-08-19, the second from 2014-01-01 to 2018-12-31. 

When I try to 'select' from the inventory at a given time `inv.select(time=obspy.UTCDateTime(2017,1,1))` nothing is returned. What I would expect is that the identical inventory is returned, still duplicate. Or at least the first, or second, or either. But at least something. 

Filtering by starttime or endtime e.g. `inv.select(endtime=obspy.UTCDateTime(2017,1,1))` returns the first network (inv[0]) and the second (inv[-1]) respectively, which is what I would generally expect. 

Using a _slightly_ custom branch but same thing occurs on 1.2.1 as well

Thanks,

**Comment by ThomasLecocq** [comment] 2021-07-27 14:15
Hi,

The problem is not your ``networks``, but your ``stations`` :

```
>>> inv.networks[0].stations

[Station NAPU (Napu Village, N Sumba Island, Indonesia)
	Station Code: NAPU
	Channel Count: None/None (Selected/Total)
	2017-05-25T00:01:59.700000Z - 2018-12-13T04:46:25.620000Z
	Access: open 
	Latitude: -9.39, Longitude: 119.93, Elevation: 199.0 m
	Available Channels:
		NAPU..BHZ]

>>> inv.networks[-1].stations
		
[Station NAPU (Napu village, north Sumba Island Indonesia)
	Station Code: NAPU
	Channel Count: 20/20 (Selected/Total)
	2014-10-20T00:00:00.000000Z - 2016-12-31T23:59:59.000000Z
	Access: closed 
	Latitude: -9.39, Longitude: 119.93, Elevation: 217.0 m
	Available Channels:
		NAPU..BHZ]
```

which means no station is present on 2017-01-01 :-)

**Comment by ThomasLecocq** [comment] 2021-07-27 14:17
Closing for now, feel free to comment here if you don't agree all is working like expected. Tom

**Closed by ThomasLecocq** 2021-07-27 14:17 UTC
Labels: .core.inventory
