### ISSUE TITLE
behaviour of plot(type='relative')

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1075] opened 2015-06-05 08:50 UTC
Hey,

is this supposed to be the behaviour of the "relative" type plot ?

``` python
from obspy.core import read

st = read()

st[0].stats.starttime += 0
st[1].stats.starttime += 20
st[2].stats.starttime += 30

st.plot(type='relative')
```

![figure_1](https://cloud.githubusercontent.com/assets/916937/8002556/2c2455c0-0b70-11e5-9f0d-b5b319fa01f9.png)

I would expect "relative" to be such that all traces begin at 0 timing, indeed allowing to compare events which occur at different times ? The doc states:

```
reftime (UTCDateTime, optional) 
    The reference time to which the relative scale will refer. 
     Defaults to starttime.
```

Which I understand as "defaults to the starttime of each Trace", not "to the min(starttime) of all Traces" ?

**Comment by krischer** [comment] 2015-06-05 10:24
Hmm..I never used this but I would expect the same as you so from my point of view this should be fixed. Other opinions?

**Comment by megies** [comment] 2015-06-05 12:30
I would prefer this to stay as is. I would find it extremely surprising to have one common time axis with differing time base. The docstring is sloppy and should be improved I admit. But it doesn't make any sense at all to me to have a `reftime` option if in the default case each trace has a different `reftime` .

If there really is much need for this I would rather introduce a new option.

**Comment by QuLogic** [comment] 2015-06-05 19:53
`Defaults to starttime.` means equal to the `starttime` argument. This is working as intended.

As you can see in the title, it's relative to _one_ time; why should the individual traces be shifted exactly?

**Comment by ThomasLecocq** [comment] 2015-06-08 12:28
Well, if you think of a single event recorded by many stations, then you are right.. But, if you think of different events recorded at the same station, same component, then you might want to show the traces relative to some other reference, for example `t0`, in order to easily "batch-"process them afterwards. For example, these are 4 events located at about the same location, recorded by the same station:

![dieppe](https://cloud.githubusercontent.com/assets/916937/8034704/7ce96eec-0dea-11e5-9b21-cbad4b56e565.jpg)

**Comment by megies** [comment] 2015-06-08 15:56
I fully understand your use case.
Still, I would argue that it's simply some different usage that could easily be covered by introducing a new `type` option but rather not by changing an option that has been around for years.

**Comment by ThomasLecocq** [comment] 2015-06-09 06:42
I agree...

Let's brainstorm for a name... 

`type` = `trace_relative` ?

**Comment by EPAnt** [comment] 2015-06-12 13:51
What about:

type = trace_absolute_relative ? When we want all traces to be aligned to
an absolute reference time-frame?

I also think this would be very useful for plotting many waveforms
together, specially when comparing event waveforms or waveforms from the
same station as given in the previous example..


Emanuel Antunes

Research Assistant (FCT Fellowship - BI)
Seismology Laboratory - Complexo Interdisciplinar
CERENA, IST, Universidade de Lisboa
Av. Rovisco Pais, 1
1049-001 Lisboa, Portugal

E: antunes.emanuel@gmail.com
E: emanuel.antunes@tecnico.ulisboa.pt


2015-06-09 7:43 GMT+01:00 Thomas Lecocq <notifications@github.com>:

**Comment by megies** [comment] 2022-10-14 13:45
stale, closing.

**Closed by megies** 2022-10-14 13:45 UTC
Labels: question, .imaging
