### ISSUE TITLE
trace.resample(window='hanning', ..) ==> change to 'hann'

### ISSUE THREAD

**Issue by mikehagerty** [obspy/obspy#3147] opened 2022-09-20 22:14 UTC
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

scipy v. 1.9.1 
scipy.signal.get_window(window) recognizes window=='hann' but not 'hanning'
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html

Please change default window='hann' for trace.resample()

Thanks!

### Code to Reproduce

```python
This works:
tr.resample(1/dt, window='hann', strict_length=False, no_filter=True)

This does not:
tr.resample(1/dt, strict_length=False, no_filter=True)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/scipy/signal/windows/_windows.py", line 2214, in get_window
    beta = float(window)
ValueError: could not convert string to float: 'hanning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/scipy/signal/windows/_windows.py", line 2232, in get_window
    winfunc = _win_equiv[winstr]
KeyError: 'hanning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mth/mth/python_pkgs/mttime/examples/notebooks/02_Prepare_Data_and_Synthetics_For_Inversion.py", line 106, in <module>
    tr.resample(1/dt, strict_length=False, no_filter=True)
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/obspy/core/util/decorator.py", line 237, in skip_if_no_data
    return func(*args, **kwargs)
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/obspy/core/trace.py", line 282, in _add_processing_info
    result = func(*args, **kwargs)
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/obspy/core/trace.py", line 1744, in resample
    large_w = np.fft.ifftshift(get_window(window,
  File "/Users/mth/miniforge3/envs/mttime/lib/python3.9/site-packages/scipy/signal/windows/_windows.py", line 2234, in get_window
    raise ValueError("Unknown window type.") from e
ValueError: Unknown window type.
```

### ObsPy Version?

obspy v1.3.0 python 3.9.13 scipy 1.9.1

### Operating System?

OS/X

### Python Version?

3.9.13

### Installation Method?

conda

**Comment by d-chambers** [comment] 2022-09-20 22:42
Duplicate of #3129, see #3116 and [this discussion](https://discourse.obspy.org/t/stream-resample-unknown-window-type-hanning-scipy-1-9-deprecation-known-issue/1479/2).

**Comment by megies** [comment] 2022-09-21 11:18
@mikehagerty hopin to push out 1.3.1 soon which has this fixed, thanks.

**Closed by megies** 2022-09-21 11:18 UTC
Labels: bug-unconfirmed
