### ISSUE TITLE
TauP issue for some depths using custom models

### ISSUE THREAD

**Issue by aceciliad** [obspy/obspy#2682] opened 2020-07-14 13:30 UTC
I want to get the travel times for some simple custom models of Mars. But for some of them i get the error:

_Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.6/site-packages/obspy/taup/tau_model.py", line 228, in load_from_depth_cache
    value = self._depth_cache.pop(depth)
KeyError: 60.0_

And then the message: 

_"TauBranch depths not compatible with slowness sampling."
obspy.taup.helper_classes.TauModelError: TauBranch depths not compatible with slowness sampling._

It works fine with Taup but not with obspy.taup, and this error only appears when considering sources between 60-80km depth.

One of the models is this one (i also tried the same model but with solid outer-core and still getting same error): 

```
     0.000   2.8622   1.6541   1.7004
     1.000   2.8622   1.6541   1.7004
     1.000   5.3851   3.1126   2.3155
    10.000   5.3851   3.1126   2.3155
    10.000   5.3847   3.1126   2.4316
    39.174   5.3847   3.1126   2.4316
    39.174   5.3850   3.1126   2.4330
    80.000   5.3850   3.1126   2.4330
mantle
    80.000   8.4775   4.7507   3.7300
   200.000   8.4775   4.7507   3.7300
   200.000   8.9174   4.9508   3.9233
   400.000   8.9174   4.9508   3.9233
   400.000   8.9116   4.8169   3.9625
   900.000   8.9116   4.8169   3.9625
   900.000  10.6193   5.6744   4.5620
  1550.000  10.6193   5.6744   4.5620
outer-core
  1550.000   5.8950   0.0000   8.9500
  3360.000   5.8950   0.0000   8.9500
inner-core
  3360.000  10.6193   5.6744   4.5620
  3389.500  10.6193   5.6744   4.5620
```

An example code is:

````
from obspy.taup import taup_create, TauPyModel
taup_create.build_taup_model('model_1.nd', output_folder='output')
model_Tau = TauPyModel('output/model_1.npz')
arr_p   = model_Tau.get_travel_times(source_depth_in_km=60.0, distance_in_degree=30.0, phase_list=['P'])
````

Using Obspy 1.2.2 and Python 3.6.9

**Comment by sstaehler** [comment] 2020-11-19 10:15
any news on this? Or would a taup developer have an idea on how to debug this?

**Comment by megies** [comment] 2020-11-19 10:36
@sstaehler if you can reproduce this with the original Java TauP, you might be able to have @crotwell have a look

**Comment by aceciliad** [comment] 2020-11-19 11:25
With the original Java TauP the model works perfectly fine for all the range of depths. 

And with obspy.taup it crashes only for source's depths between 60-80km. For example for:

`arrivals = model.get_travel_times(source_depth_in_km=59,distance_in_degree=30, phase_list=['S'])'

it works.
But for:

`arrivals = model.get_travel_times(source_depth_in_km=60,distance_in_degree=30, phase_list=['S'])'

it crashes with the error mentioned before

**Comment by megies** [comment] 2020-11-19 13:36
Alright, then it's a problem on our end. That being said, we haven't had much luck finding volunteers to work on obspy.taup problems.. sooo.. :man_shrugging:

**Comment by crotwell** [comment] 2020-11-19 14:33
I don't think I can dig into the python to fix this, but I suspect that the issue is caused by your model having quite a lot of high slowness zones (ie low velocity zones). They are certainly possible, but physics says they should be kind of rare since increasing pressure should, in the absence of material property changes, cause an increase in velocity with depth. Given the very small changes in velocity in your model, I am guessing you are trying to do some kind of inverse modeling problem with small perturbations. If so, you may wish to impose criteria on those perturbations to avoid decreases in velocity with depth. 

While the code probably should be able to handle this type of model, low velocity layers cause lots of numerical complexity that should probably be avoided if possible.

**Comment by sstaehler** [comment] 2020-11-19 22:08
Hi @crotwell, thanks for the explanation! As you may have guessed, the model is not Earth and on Mars, a relatively high thermal gradient may indeed cause quite pronounced low velocity layers.

The thing we are wondering is why it's working with the original taup and which routes there are in the obspy taup for debugging.

**Comment by crotwell** [comment] 2020-11-19 22:29
Sorry I don't know the answer to that. I have made some changes in the past few years related to low velocity zones that could be related. Those changes may post-date the translation from java to python, I am unsure of what version was used for that. It is possible that commits since then could be ported over, but I am not familiar enough with how the java to python conversion was done to even begin to think about it.

The java version is on github too, so all changes are visible. Just not sure how to migrate them.

https://github.com/crotwell/TauP

**Comment by sstaehler** [comment] 2022-03-29 05:22
came back to this. What surprises me a bit is the != comparison of two float variables in 
https://github.com/obspy/obspy/blob/6e1c0276aabfb22ae6972d30ca07c8598afd0659/obspy/taup/tau_branch.py#L123

I mean, do we expect that to work with floats _every_ time? Wouldn't it be more prudent to use np.isclose here?

**Comment by sstaehler** [comment] 2022-03-29 05:35
This solution is maybe a bit dirty, but at least it produces reasonable results for me. The travel times and slownesses are continuous across a depth range where the code was crashing before.

```
        if not(np.isclose(top_s_layer['top_depth'], self.top_depth, atol=1e-5, rtol=1e-6) \
                or np.isclose(bot_s_layer['bot_depth'], self.bot_depth, atol=1e-5, rtol=1e-6)):
            raise TauModelError(
                "TauBranch depths not compatible with slowness sampling.")
        else:
            if top_s_layer['top_depth'] != self.top_depth:
                self.top_depth = top_s_layer['top_depth']
            if bot_s_layer['bot_depth'] != self.bot_depth:
                self.bot_depth = bot_s_layer['bot_depth']

```
The last two statements are necessary, because the identity of self.bot_depth and bot_s_layer['bot_depth'] is expected elsewhere....

**Comment by megies** [comment] 2022-05-05 13:02
@aceciliad you could check if #3062 fixes your problem

**Comment by johnrudge** [comment] 2022-06-05 10:34
Sorry, I didn't notice that the model_1.nd was in the original post. I have checked the example given and can confirm it is fixed in `master`.
```
3 arrivals
        P phase arrival at 212.297 seconds
        P phase arrival at 217.001 seconds
        P phase arrival at 217.041 seconds
```

**Closed by johnrudge** 2022-06-05 10:34 UTC
Labels: .taup

**Comment by megies** [comment] 2022-06-07 11:18
Awsome, thanks for checking @johnrudge!
