### ISSUE TITLE
tr.remove_response hangs

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#1970] opened 2017-10-25 03:17 UTC
hi, 

using a station.xml file (derived from obspy recipe / inv.write) and a single 24hr 250hz mseed file

e.g.
NZ.HR1.10.EHZ | 2016-11-22T00:00:00.000000Z - 2016-11-22T23:59:59.996000Z | 250.0 Hz, 21600000 samples

attempting to remove this response ala: tr.remove_response(inventory=inv)

that command essentially crashes my computer (slows it down infinitely until the mouse can't move) but without any real warnings or errors that i can see. if i wait long enough it will recover, or if i manage to control-c the window before things get out of hand. 

here's the traceback post-exiting

```
`<decorator-gen-140> in remove_response(self, inventory, output, water_level, pre_filt, zero_mean, taper, taper_fraction, plot, fig, **kwargs)

/usr/local/lib/python2.7/dist-packages/obspy-1.1.0rc10.post0+dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/core/trace.pyc in _add_processing_info(func, *args, **kwargs)
    230     info = info % "::".join(arguments)
    231     self = args[0]
--> 232     result = func(*args, **kwargs)
    233     # Attach after executing the function to avoid having it attached
    234     # while the operation failed.

/usr/local/lib/python2.7/dist-packages/obspy-1.1.0rc10.post0+dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/core/trace.pyc in remove_response(self, inventory, output, water_level, pre_filt, zero_mean, taper, taper_fraction, plot, fig, **kwargs)
   2819         freq_response, freqs = \
   2820             response.get_evalresp_response(self.stats.delta, nfft,
-> 2821                                            output=output, **kwargs)
   2822 
   2823         if plot:

/usr/local/lib/python2.7/dist-packages/obspy-1.1.0rc10.post0+dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/core/inventory/response.pyc in get_evalresp_response(self, t_samp, nfft, output, start_stage, end_stage)
   1429 
   1430         response = self.get_evalresp_response_for_frequencies(
-> 1431             freqs, output=output, start_stage=start_stage, end_stage=end_stage)
   1432         return response, freqs
   1433 

/usr/local/lib/python2.7/dist-packages/obspy-1.1.0rc10.post0+dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/core/inventory/response.pyc in get_evalresp_response_for_frequencies(self, frequencies, output, start_stage, end_stage)
   1391         output, chan = self._call_eval_resp_for_frequencies(
   1392             frequencies, output=output, start_stage=start_stage,
-> 1393             end_stage=end_stage)
   1394         return output
   1395 

/usr/local/lib/python2.7/dist-packages/obspy-1.1.0rc10.post0+dirty.obspy.master-py2.7-linux-x86_64.egg/obspy/core/inventory/response.pyc in _call_eval_resp_for_frequencies(self, frequencies, output, start_stage, end_stage, hide_sensitivity_mismatch_warning)
   1350             rc = clibevresp._obspy_calc_resp(C.byref(chan), frequencies,
   1351                                              len(frequencies),
-> 1352                                              output, out_units, -1, 0, 0)
   1353             if rc:
   1354                 e, m = ew.ENUM_ERROR_CODES[rc]

KeyboardInterrupt: 

```

i'm wondering if the file size is too large (~10mb) but i can't imagine it is. i can run tr.detrend("demean"); tr.detrend("linear") on the same trace in a second or two. 

i use the same station.xml response in seiscomp3 and it works fine, and i can see the original waveform, the response, and the corrected waveform. but is there something in there (wrong sample rate or ?) that could be causing this?

i was using obspy-master from a few months ago, updated to today's and have the same problem. i have NOT tried it on the regular release (out of laziness). 

any help appreciated

**Comment by megies** [comment] 2017-10-25 10:22
Is there a strong need to do the instrument response removal for the whole day in one step? Also 10MB on disk doesn't mean the file won't be larger in memory, itwill be several hundred MB in RAM.

**Comment by krischer** [comment] 2017-10-25 10:29
Hmm - it might be slow for this number of samples but note that it does not hang in the FFT but within evalresp. Maybe the response somehow trips it up? Two comments:

* Can you trim the file to a couple of minutes and try again?
* Can you upload both files somewhere?

**Comment by filefolder** [comment] 2017-10-25 23:28
ok, i tried a smaller file size ( ~2 hours @ 250 hz / 1.3mb ) and it WORKS... (sorry i should have tried this first!) 

it still takes almost 40 seconds or so which seems abnormally long? granted this workstation is no spring chicken but it's still got 8 gb ram so i must just be underestimating the work involved. 

regardless seems like i could just break a daily file into shards, process those, and piece it all back together but that looks like it will take a week of continuous processing just to run a half a year of a single station. is there a more efficient way to process this in obspy than the cookbook inv=inventory(blah.xml); tr.remove_response(inventory=inv) ? 

n.b. this is a non-seismologist colleague's data, what they're doing with it or why they need to pre-process it like this is a bit beyond me, i'm just trying to help

**Comment by filefolder** [comment] 2017-10-25 23:47
last comment-- 95% chance this is some weird glitch on my end so feel free to close. need to start budgeting in "new computers" in these grants once in a while.

**Comment by barsch** [comment] 2017-10-26 00:47
why don't you upload this 2h file and show us how you process them so we have a chance to debug/profile it and maybe find a way to optimize it

**Comment by filefolder** [comment] 2017-10-26 01:05
sure, although this data is at 500 hz (don't ask)

```
responsexml="station.xml"
inv = read_inventory(responsexml)
st = read("twohour.mseed")
tr = st[0]
tr.remove_response(inventory=inv)

```
clocked at 92 seconds 8 core 8 gig workstation. the only thing i can think of is that float64 might be a bit overkill, is there an obvious way to do this in 32 or even 16?


[ex.zip](https://github.com/obspy/obspy/files/1416637/ex.zip)

**Comment by filefolder** [comment] 2017-10-27 01:03
FWIW same problem with tr.resample(250.)... even a 2 hour/500hz file takes well over 10 minutes. 

seems to absolve the inventory file being the culprit. 

my numpy & scipy versions are 1.11 & 0.17

**Comment by krischer** [comment] 2017-11-13 09:52
Sorry for the late reply - can you upload the file somewhere? I absolutely cannot reproduce on my machine.

```python
In [6]: tr
Out[6]: BW.RJOB..EHZ | 2009-08-24T00:20:03.000000Z - 2009-08-24T02:20:02.998000Z | 500.0 Hz, 3600000 samples

In [7]: %timeit tr.resample(250.0)
241 ms ± 6.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by filefolder** [comment] 2017-12-06 05:42
i ended up upgrading the CPUs on this workstation to 3GHZ and the problem isn't nearly noticeable now, in the meantime i've more or less moved on. if no one else is seeing it i'm nearly certain it was just something weird going on on my end. recommend close ticket.

**Comment by barsch** [comment] 2017-12-06 05:44
thanks for the feedback! closing ...

**Closed by barsch** 2017-12-06 05:44 UTC
Labels: .signal, question
