### ISSUE TITLE
error getting Proj version

### ISSUE THREAD

**Issue by frodo4fingers** [obspy/obspy#2449] opened 2019-09-11 09:00 UTC
# can't import Client to get data

## my settings
+ manjaro linux
+ obspy installed via AUR
+ python 3.7.4, numpy 1.17.0, obspy is either 1.1.1-1 (AUR, or 0.0.0+archive from `obspy.__version__`), pyproj 2.3.0, Proj 6.1.0-1

## problem
`from obspy.clients.fdsn import Client` causes the following:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/usr/lib/python3.7/site-packages/obspy/core/__init__.py", line 125, in <module>
    from obspy.core.util.attribdict import AttribDict  # NOQA
  File "/usr/lib/python3.7/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/usr/lib/python3.7/site-packages/obspy/core/util/base.py", line 398, in <module>
    PROJ4_VERSION = get_proj_version()
  File "/usr/lib/python3.7/site-packages/obspy/core/util/base.py", line 383, in get_proj_version
    version_string = str(Proj(proj='utm', zone=10, ellps='WGS84').proj_version)
AttributeError: 'Proj' object has no attribute 'proj_version'
```
tbh i hardcoded the current version number in there to get it running for the moment... :-/

**Comment by heavelock** [comment] 2019-09-11 11:16
Duplicate of https://github.com/obspy/obspy/issues/2445.
Pyproj has to be in version 1.9.5.1

**Closed by heavelock** 2019-09-11 11:16 UTC

**Comment by megies** [comment] 2019-09-11 11:19
> Pyproj has to be in version 1.9.5.1

I'm confused.. why should we need a highly specific version of pyproj, @heavelock?

**Comment by heavelock** [comment] 2019-09-11 11:28
Due issue that is being solved in (Derrick's comment): https://github.com/obspy/obspy/pull/2442 
Pyproj > 2 changed API. Before we ship this PR, in case of python 3.7 the pyproj has to be <2.

**Comment by megies** [comment] 2019-09-11 12:58
OK, gotcha. @heavelock 

@frodo4fingers you should report this necessary pinning on https://aur.archlinux.org/packages/python-obspy/ in comments. I would've done it but this AUR site has the dumbest bot-protection in registration I have ever seen. Basically you can't register if you don't have an archlinux machine or do some serious online research because it wants some stdout of an Archlinux-specific command not available on any other system. It's incredible.
