### ISSUE TITLE
Seisan format file reading error

### ISSUE THREAD

**Issue by nikosT** [obspy/obspy#1875] opened 2017-09-04 12:04 UTC
Hi,
I'm trying to read a seisan format file but I get this error. 

Running code:
```python
from obspy import read
s=read('D1360930.203', format='seisan')
````

Result:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-31>", line 2, in read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 235, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-32>", line 2, in _read
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/decorator.py", line 211, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/stream.py", line 277, in _read
    headonly=headonly, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/core/util/base.py", line 433, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/obspy/io/seisan/core.py", line 175, in _read_seisan
    temp = _readline(fh, 1040).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfb in position 0: ordinal not in range(128)
```

The file is attached in zip format here:
[D1360930.203.zip](https://github.com/obspy/obspy/files/1274607/D1360930.203.zip)

**Comment by barsch** [comment] 2017-09-04 12:08
file is seisan version 6 which is currently not support (see also https://github.com/obspy/obspy/issues/1864)

however, I already started to work on it - hope to finish it end of the week ...

would be a big help if you could provide the same file in another format - e.g. mseed or ascii if possible at all

**Comment by nikosT** [comment] 2017-09-04 12:12
The MSEED file is attached in zip format here:
[D1360930.203_MSEED.zip](https://github.com/obspy/obspy/files/1274621/D1360930.203_MSEED.zip)

**Comment by barsch** [comment] 2017-09-04 12:12
perfect - thanks!

**Comment by megies** [comment] 2017-09-04 13:01
Closing this as a duplicate of #1864. @nikosT you can go to #1864 and click on "Notifications: subscribe" in the right side bar of the PR to get notified on any news on this matter.

**Closed by megies** 2017-09-04 13:01 UTC
