### ISSUE TITLE
Bug with using Linux Azure Functions on a Consumption Plan - issue with read_inventory

### ISSUE THREAD

**Issue by jpdc-developer** [obspy/obspy#2803] opened 2021-03-03 21:02 UTC
# Issue and Example:

Running read_inventory on a Linux Azure Function fails on a consumption plan, but succeeds on a Linux Azure Function on a dedicated plan.

The error is like:

```
_read_from_plugin raise TypeError('Unknown format for file %s' % filename)Result: Failure Exception: TypeError: Unknown format for file
```

I got the station xml file by using get_stations and providing a filename to it. Once saved, it gets read by read_inventory into an inventory object.

## Some things I have tried:
- running read_from_plugin on a consumption plan while making sure it's using the correct /tmp/ temp directory. 
- Trying out that read_from_plugin can read a filename like 'obspy-0yop00ed.tmp'
- Identifying that read_from_plugin works when providing format = 'STATIONXML', and when omitting the specific argument

read_inventory fails but read_from_plugin works when providing the expected arguments on a consumption plan. Would you be able to provide guidance on how to figure out what is wrong with running it on a consumption plan? Maybe it gets supplied with the wrong format somehow?  

## Context:

I have been trying to use ``get_stations`` to get station data, but had issues with it when running on a Linux consumption plan on Azure. I found a workaround -- use a dedicated (app service) plan on azure. I logged this under my [post on the obspy forum about a get_stations bug](https://discourse.obspy.org/t/trying-to-get-stations-into-inventory-using-client-but-failing-in-linux-azure-function/1117/3). 

However, I want to use a consumption plan for cost and performance purposes (we need to be able to run more instances of the function instead of being limited to its tier's limit). 

# Environment:

ObsPy version = 1.2.2, Python version = 3.8.6 and Platform Linux (Azure Function)
Installed ObsPy using Pip, Python using the downloadable installer

**Comment by jpdc-developer** [comment] 2021-04-06 02:27
Hi @calum-chamberlain , @ThomasLecocq , @megies,

This post is similar to a previous post you commented on about using ObsBy in Azure.

I was wondering if you can comment on and give any insight as I am having trouble with it. There haven't been any responses so far.

Also, if you think anyone else can help solve this issue, please feel free to send them this post or tag them. Thanks :)

**Comment by ThomasLecocq** [comment] 2021-04-06 08:02
you need to restart the kernel, reboot, reinitialize the environment, deactivate/reactivate, ... whatever makes python re-read the entry points properly ... The issue is that obspy is there, but none of its entry points are "present", so the "plugins", I/O, etc, are not found/available.

**Comment by ThomasLecocq** [comment] 2022-01-05 13:18
I suspect this is solved by now, closing (reopen if still valid)

**Closed by ThomasLecocq** 2022-01-05 13:18 UTC
