### ISSUE TITLE
Can't use obspy 1.2.2 on OSX Mojave

### ISSUE THREAD

**Issue by mhearne-usgs** [obspy/obspy#2824] opened 2021-04-02 21:40 UTC
I suspect that given the number of combinations of packages, this may not be an obspy problem but rather a conda problem manifesting itself with obspy. I'm curious if anyone has seen this before?

OSX version: 10.14.6
Python version: 3.8.8, 3.7, 3.6
Obspy version: 1.2.1, 1.2.2
When I install obspy 1.2.2 using conda, I get an un-importable version of the package.

`conda create -n testobspy python=3.8 obspy`

```
>>> import obspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mhearne/miniconda/envs/testobspy/lib/python3.8/site-packages/obspy/__init__.py", line 60, in <module>
    _add_format_plugin_table(read, "waveform", "read", numspaces=4)
  File "/Users/mhearne/miniconda/envs/testobspy/lib/python3.8/site-packages/obspy/core/util/base.py", line 562, in _add_format_plugin_table
    if '%s' in func.__doc__:
TypeError: argument of type 'NoneType' is not iterable
>>> 
```

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by mhearne-usgs** [comment] 2021-04-02 21:48
I am having the same problem with pip installed version of obspy.

**Comment by QuLogic** [comment] 2021-04-03 03:59
It looks like you're running with `python3 -O`, or set `PYTHONOPTIMIZE` in the environment.

**Comment by mhearne-usgs** [comment] 2021-04-04 02:13
Well I wasn't doing that intentionally, and now of course when I run the same commands to create and test the environment, I no longer get the same error.

**Comment by barsch** [comment] 2021-04-04 05:20
closing for now - please open again if you can reproduce this issue

**Closed by barsch** 2021-04-04 05:20 UTC
